export const id="0021_customer_workflow";
export async function up(db){const bytes=column=>db.kind==="postgres"?"octet_length("+column+")":"length(CAST("+column+" AS BLOB))";await db.exec(`
 CREATE TABLE conversation_revisions(
 id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,lead_id TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision=CAST(revision AS INTEGER) AND revision BETWEEN 1 AND 2147483647),expected_revision INTEGER NOT NULL CHECK(expected_revision=revision-1),
 status TEXT NOT NULL CHECK(status IN('OPEN','RESOLVED','ESCALATED')),assigned_owner_id TEXT,read_inbound_token TEXT CHECK(read_inbound_token IS NULL OR length(read_inbound_token)=64),resolved_inbound_token TEXT CHECK(resolved_inbound_token IS NULL OR length(resolved_inbound_token)=64),forced_unread INTEGER NOT NULL CHECK(forced_unread IN(0,1)),observed_inbound_token TEXT NOT NULL CHECK(length(observed_inbound_token)=64),inbound_count INTEGER NOT NULL CHECK(inbound_count=CAST(inbound_count AS INTEGER) AND inbound_count>=0),last_inbound_message_id TEXT,
 request_key TEXT NOT NULL CHECK(length(request_key) BETWEEN 1 AND 200),request_hash TEXT NOT NULL CHECK(length(request_hash)=64),reason TEXT NOT NULL CHECK(length(reason) BETWEEN 1 AND 2000),created_at TEXT NOT NULL,created_by TEXT NOT NULL,
 UNIQUE(organization_id,lead_id,revision),UNIQUE(organization_id,request_key),UNIQUE(organization_id,id),
 FOREIGN KEY(organization_id,lead_id) REFERENCES leads(organization_id,id),FOREIGN KEY(organization_id,assigned_owner_id) REFERENCES users(organization_id,id),FOREIGN KEY(organization_id,created_by) REFERENCES users(organization_id,id),FOREIGN KEY(organization_id,lead_id,last_inbound_message_id) REFERENCES channel_messages(organization_id,lead_id,id));
 CREATE INDEX idx_conversation_history ON conversation_revisions(organization_id,lead_id,revision DESC);
 CREATE INDEX idx_inbox_message_scope ON channel_messages(organization_id,lead_id,direction,created_at,id);
 CREATE UNIQUE INDEX idx_followup_scoped_identity ON follow_up_tasks(organization_id,lead_id,id);
 CREATE TABLE follow_up_commands(
 id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,lead_id TEXT NOT NULL,follow_up_id TEXT NOT NULL,operation TEXT NOT NULL CHECK(operation IN('CREATE','RESCHEDULE','COMPLETE','CANCEL')),expected_task_token TEXT CHECK(expected_task_token IS NULL OR length(expected_task_token)=64),
 request_key TEXT NOT NULL CHECK(length(request_key) BETWEEN 1 AND 200),request_hash TEXT NOT NULL CHECK(length(request_hash)=64),before_json TEXT CHECK(before_json IS NULL OR ${bytes("before_json")}<=16384),after_json TEXT NOT NULL CHECK(${bytes("after_json")}<=16384),reason TEXT NOT NULL CHECK(length(reason) BETWEEN 1 AND 2000),created_at TEXT NOT NULL,created_by TEXT NOT NULL,
 CHECK((operation='CREATE' AND expected_task_token IS NULL) OR(operation<>'CREATE' AND expected_task_token IS NOT NULL)),UNIQUE(organization_id,request_key),UNIQUE(organization_id,id),
 FOREIGN KEY(organization_id,lead_id) REFERENCES leads(organization_id,id),FOREIGN KEY(organization_id,lead_id,follow_up_id) REFERENCES follow_up_tasks(organization_id,lead_id,id),FOREIGN KEY(organization_id,created_by) REFERENCES users(organization_id,id));
 CREATE INDEX idx_followup_command_history ON follow_up_commands(organization_id,follow_up_id,created_at,id);
 CREATE TABLE business_outcomes(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,lead_id TEXT NOT NULL,slot TEXT NOT NULL CHECK(slot IN('QUALIFIED_CONVERSATION','MEETING_BOOKED','QUOTE_REQUESTED','RESULT')),created_at TEXT NOT NULL,created_by TEXT NOT NULL,UNIQUE(organization_id,lead_id,slot),UNIQUE(organization_id,lead_id,id),UNIQUE(organization_id,id),FOREIGN KEY(organization_id,lead_id) REFERENCES leads(organization_id,id),FOREIGN KEY(organization_id,created_by) REFERENCES users(organization_id,id));
 CREATE TABLE business_outcome_revisions(
 id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,lead_id TEXT NOT NULL,outcome_id TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision=CAST(revision AS INTEGER) AND revision BETWEEN 1 AND 2147483647),expected_revision INTEGER NOT NULL CHECK(expected_revision=revision-1),status TEXT NOT NULL CHECK(status IN('RECORDED','WITHDRAWN')),kind TEXT NOT NULL CHECK(kind IN('QUALIFIED_CONVERSATION','MEETING_BOOKED','QUOTE_REQUESTED','WON','LOST')),occurred_at TEXT NOT NULL,summary TEXT NOT NULL CHECK(length(summary) BETWEEN 1 AND 2000),source_reference TEXT CHECK(source_reference IS NULL OR length(source_reference) BETWEEN 1 AND 500),evidence_message_id TEXT,attributed_action_id TEXT,attribution_note TEXT CHECK(attribution_note IS NULL OR length(attribution_note) BETWEEN 1 AND 2000),amount_json TEXT CHECK(amount_json IS NULL OR ${bytes("amount_json")}<=1024),request_key TEXT NOT NULL CHECK(length(request_key) BETWEEN 1 AND 200),request_hash TEXT NOT NULL CHECK(length(request_hash)=64),reason TEXT NOT NULL CHECK(length(reason) BETWEEN 1 AND 2000),created_at TEXT NOT NULL,created_by TEXT NOT NULL,
 CHECK((attributed_action_id IS NULL AND attribution_note IS NULL) OR(attributed_action_id IS NOT NULL AND attribution_note IS NOT NULL)),CHECK(amount_json IS NULL OR kind='WON'),UNIQUE(organization_id,outcome_id,revision),UNIQUE(organization_id,request_key),UNIQUE(organization_id,id),
 FOREIGN KEY(organization_id,lead_id,outcome_id) REFERENCES business_outcomes(organization_id,lead_id,id),FOREIGN KEY(organization_id,lead_id,evidence_message_id) REFERENCES channel_messages(organization_id,lead_id,id),FOREIGN KEY(organization_id,lead_id,attributed_action_id) REFERENCES actions(organization_id,lead_id,id),FOREIGN KEY(organization_id,created_by) REFERENCES users(organization_id,id));
 CREATE INDEX idx_business_outcome_history ON business_outcome_revisions(organization_id,outcome_id,revision DESC);
`);}
