import { ArrowLeft, ArrowUpRight, ShieldCheck } from "lucide-react";

export function ProductInformationPage() {
  return <main className="min-h-screen w-full self-start bg-page px-5 py-10 text-ink sm:px-8"><div className="mx-auto max-w-3xl space-y-8">
    <a href="/" className="inline-flex min-h-11 items-center gap-2 text-sm font-medium text-brand underline"><ArrowLeft size={16} aria-hidden="true" />Back to the product</a>
    <header className="space-y-3"><p className="text-sm font-medium text-brand">AI Lead Intelligence &amp; Outbound Automation</p><h1 className="font-display text-4xl font-normal leading-tight tracking-tight sm:text-5xl">Product, privacy and support information</h1><p className="text-sm text-muted">Preview information recorded 13 September 2026. This page describes current behavior and remaining publication requirements.</p></header>
    <section className="space-y-3 rounded-xl border border-line bg-surface p-5" aria-labelledby="preview-status"><h2 id="preview-status" className="text-xl font-semibold">What you can try</h2><p className="text-sm leading-7">The public example uses fictional enquiries and local, deterministic interactions. It does not send messages, create customer records or call a model. Creating a workspace opens the authenticated Sandbox product; it does not establish that a live email channel is verified.</p><p className="text-sm leading-7">AI Lead Intelligence helps inspect saved evidence, unknowns, business fit and possible next steps. Outbound Automation acts through application policy and explicit review. A saved recommendation is not contact permission or proof of a customer outcome.</p></section>
    <section className="space-y-3" aria-labelledby="pilot-data"><h2 id="pilot-data" className="text-xl font-semibold">Information in a pilot-interest request</h2><p className="text-sm leading-7">The form collects your name, work email, business name, a description of your workflow, channel preference and your agreement to store those details for review. The service also records request identity, timestamps and abuse-prevention metadata. Please provide business contact details only; leave customer records, passwords and sensitive information out of the public form.</p><p className="text-sm leading-7">Requests are stored separately from workspace leads. A successful response means the request is saved for review. It does not confirm a pilot place, booking, response time or live-channel access. Submitting the form does not automatically send an email.</p><div className="rounded-lg border border-line bg-surface p-4"><h3 className="font-semibold">Retention policy: 90 days</h3><p className="mt-2 text-sm leading-7">The declared policy is to remove pilot-interest records after 90 days. Retention needs an operating purge process and an accountable operator; this preview page does not confirm that a scheduled purge has run. These requirements must be verified before public publication.</p></div></section>
    <section className="space-y-3" aria-labelledby="workspace-data"><h2 id="workspace-data" className="text-xl font-semibold">Workspace and provider data</h2><p className="text-sm leading-7">Signing in uses an account session. Authenticated workspaces store the enquiries, source facts, assessments, messages and audit records needed by the product. The pilot-interest policy above does not describe retention for all workspace records.</p><p className="text-sm leading-7">A configured model or messaging provider can process information required for the explicitly used capability. Actual provider choices, hosting location, workspace retention and responsibilities must be reviewed for the intended deployment. This preview does not promise a particular residency, certification or universal provider policy.</p></section>
    <section className="space-y-3 rounded-xl border border-warning/30 bg-warning/5 p-5" aria-labelledby="operator-contacts"><h2 id="operator-contacts" className="flex items-center gap-2 text-xl font-semibold"><ShieldCheck size={20} aria-hidden="true" />Privacy and support contacts</h2><p className="text-sm leading-7">The responsible operator's identity, privacy-request contact, support contact and support hours have not been published for this preview. There is no advertised response SLA or automated email-recovery service.</p><p className="text-sm leading-7">Public publication requires these details and a working way to request access, correction or deletion of submitted information. If you do not already know the responsible operator, avoid sending personal or sensitive information until those contacts are available.</p><p className="text-sm leading-7">Existing workspace owners can create offline account-recovery codes in Settings while signed in. Keep them private; this does not replace a published support contact.</p></section>
    <section className="space-y-3" aria-labelledby="availability-interest"><h2 id="availability-interest" className="text-xl font-semibold">Availability updates</h2><p className="text-sm leading-7">If workspace access is unavailable, you can separately choose to save your name, email and optional business name for product availability updates. This does not create an account. Passwords and session credentials are not collected in this request. An independently hosted intake database can retain the request even while the workspace service is offline; success is shown only when saving is confirmed. These requests expire after 90 days and are reviewed and removed through the operator process. Updates are handled by the operator; an automatic notification schedule is not promised.</p></section>
    <footer className="flex flex-wrap gap-5 border-t border-line pt-5"><a href="/#example" className="inline-flex min-h-11 items-center gap-2 text-sm text-brand underline">Try the synthetic example<ArrowUpRight size={15} aria-hidden="true" /></a><a href="/login" className="inline-flex min-h-11 items-center gap-2 text-sm text-brand underline">Sign in<ArrowUpRight size={15} aria-hidden="true" /></a></footer>
  </div></main>;
}
