import { BrandMark } from "@/components/brand-mark";
import { LoadingScreen } from "@/components/loading-screen";
import { Component, Suspense, lazy, useState, type ReactNode } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronDown, FileText, Layers3, LockKeyhole, Menu, Quote, ShieldCheck, X } from "lucide-react";
import { PilotRequestForm } from "./PilotRequestForm";
import "./landing.css";

const LandingDemo = lazy(() => import("./LandingDemo"));
class DemoBoundary extends Component<{ children: ReactNode }, { failed: boolean }> {
  state = { failed: false };
  static getDerivedStateFromError() { return { failed: true }; }
  render() { return this.state.failed ? <StaticExample failed /> : this.props.children; }
}
function StaticExample({ failed = false }: { failed?: boolean }) {
  return <div className="landing-static-example" aria-label="Readable example workflow"><div className="landing-static-label"><ShieldCheck size={16} />Interactive example — synthetic data. No messages are sent.</div>{failed && <p role="alert" className="landing-enhancement-error">The interactive example could not load. You can still read the workflow below or reload the page to try again.</p>}<div className="landing-static-flow"><div><span>01 / Source</span><Quote size={21} /><h3>“We need 12 workstations.”</h3><p>A fictional studio's enquiry names an interest and location. No budget is recorded.</p></div><ArrowRight size={22} aria-hidden="true" /><div><span>02 / Intelligence</span><Layers3 size={21} /><h3>A match with an unknown.</h3><p>Interest matches the sample offering. Budget stays unknown, so business fit needs review.</p></div><ArrowRight size={22} aria-hidden="true" /><div><span>03 / Next move</span><ShieldCheck size={21} /><h3>Review a useful question.</h3><p>An operator checks a clarification draft. A later opt-out would block further contact.</p></div></div></div>;
}
const questions = [
  ["Does the example send a message?", "No. It uses fictional enquiries and runs in your browser. Nothing is uploaded or sent."],
  ["Can I start with my existing enquiries?", "Yes. The application supports CSV import with a mapping review, original enquiry context and your own business criteria. Start with a small set of records you have permission to use."],
  ["Which live channels are available?", "Live sending is not yet available. You can explore the workflow in Sandbox. Tell us which channel matters to your business when you reach out; choosing one in the form records your interest, rather than enabling it."],
  ["What happens when I request a pilot?", "We save your contact details and workflow description for review. A demo time or pilot place is agreed separately. Sending a request does not create a workspace or confirm a booking."],
  ["What does the example prove?", "It shows how an enquiry can move from context to a reviewed decision. It uses synthetic data, so it does not demonstrate customer results or guarantee a business outcome."],
];

export function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  function openExample() { setMenuOpen(false); }
  return <div className="landing-page">
    <a href="#main-content" className="landing-skip-link">Skip to content</a>
    <header className="landing-header"><a href="/" className="landing-brand" aria-label="Relay — AI Lead Intelligence & Outbound Automation home"><BrandMark className="landing-brand-icon" /><span><strong>Relay</strong><small>AI Lead Intelligence<br />&amp; Outbound Automation</small></span></a><nav className="landing-desktop-nav" aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#example" onClick={openExample}>Try it out</a><a href="#get-started">Getting started</a></nav><div className="landing-header-actions"><a href="/login" className="landing-sign-in">Sign in<ArrowUpRight size={15} /></a><a href="/register" className="landing-button landing-button-dark landing-header-cta">Get started<ArrowUpRight size={15} /></a><button type="button" className="landing-menu-toggle" aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen} aria-controls="landing-mobile-menu" onClick={() => setMenuOpen(value => !value)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div>
      {menuOpen && <nav id="landing-mobile-menu" className="landing-mobile-menu" aria-label="Mobile navigation"><a href="#how-it-works" onClick={() => setMenuOpen(false)}>How it works</a><a href="#example" onClick={openExample}>Try it out</a><a href="#get-started" onClick={() => setMenuOpen(false)}>Getting started</a><a href="/login">Sign in</a><a href="/register">Get started</a></nav>}
    </header>
    <main id="main-content">
      <section className="landing-hero" aria-labelledby="landing-title"><div className="landing-hero-copy"><div className="landing-eyebrow"><span />AI Lead Intelligence &amp; Outbound Automation</div><h1 id="landing-title">Your next move,<br />backed by what<br /><em>you know.</em></h1><p>Turn scattered enquiries into explained priorities. See the evidence, review the next action, and let the response guide what follows.</p><div className="landing-hero-actions"><a href="#example" onClick={openExample} className="landing-button landing-button-dark">Try it out<ArrowUpRight size={18} /></a><a href="/register" className="landing-text-link">Get started<ArrowRight size={17} /></a></div><div className="landing-hero-note"><ShieldCheck size={15} /><span>Product preview. Synthetic example. You keep the review.</span></div></div><HeroVisual /></section>
      <div className="landing-loop-band"><span>Start with your existing enquiries</span><div><span>Source</span><ArrowRight size={15} /><span>Intelligence</span><ArrowRight size={15} /><span>Review</span><ArrowRight size={15} /><span>Response</span><span className="landing-loop-return" aria-hidden="true">↲</span></div><a href="#example" onClick={openExample} aria-label="Try the interactive workflow"><ArrowDown size={19} /></a></div>
      <section id="how-it-works" className="landing-workflow landing-section" aria-labelledby="workflow-title"><div className="landing-section-heading"><span className="landing-section-index">01 / A clearer working day</span><h2 id="workflow-title">Good enquiries deserve<br />a considered next step.</h2><p>Keep the original context close as you move from a record to a decision.</p></div><div className="landing-workflow-rows">{[
        ["01", "Bring the context together.", "Start with existing enquiries. Review mapped fields and keep the source behind each fact.", FileText],
        ["02", "Understand the fit. See the gaps.", "Use explicit business criteria. Missing or conflicting information stays visible for review.", Layers3],
        ["03", "Make a reviewed move.", "Inspect the exact message and contact restrictions. A response becomes new evidence for the next decision.", ShieldCheck],
      ].map(([number, title, description, Icon]) => { const RowIcon = Icon as typeof FileText; return <article key={String(number)}><span className="landing-row-number">{String(number)}</span><div><h3>{String(title)}</h3><p>{String(description)}</p></div><RowIcon size={27} strokeWidth={1.4} /></article>; })}</div></section>
      <section id="example" className="landing-example-section" aria-labelledby="example-title"><div className="landing-section-heading"><span className="landing-section-index">02 / Put the idea to work</span><div className="landing-example-heading-row"><h2 id="example-title">One enquiry.<br /><em>A decision you can follow.</em></h2><p>Explore three fictional enquiries, open the evidence and see how a review or reply changes what comes next.</p></div></div>
        <div className="landing-demo-mount"><DemoBoundary><Suspense fallback={<LoadingScreen compact title="Opening your interactive workspace" description="Try the workflow with sample enquiries. Nothing is sent." />}><LandingDemo /></Suspense></DemoBoundary></div><p className="landing-example-caption">A deterministic product preview, not a live workspace. Example dates are fixed in September 2026. Some illustrated workflow steps remain under development; live sending is currently held.</p>
      </section>
      <section className="landing-control-section landing-section" aria-labelledby="control-title"><div className="landing-control-art" aria-hidden="true"><div className="landing-proof-source"><span>THE SOURCE</span><p>“We need 12 workstations…”</p></div><div className="landing-proof-thread" /><div className="landing-proof-claim"><Check size={18} /><span>Interest: workstations<small>Exact source attached</small></span></div><div className="landing-proof-unknown"><span>?</span><p>Budget: unknown<small>Ask before assuming.</small></p></div><div className="landing-proof-footer"><ShieldCheck size={16} />A reason you can inspect.</div></div><div className="landing-control-copy"><span className="landing-section-index">03 / Built around review</span><h2 id="control-title">Keep the reason<br /><em>within reach.</em></h2><p>Priorities are useful when you can question them. Open the source, spot an unknown and decide whether the next move should be a message, a question or a stop.</p><ul><li><Check size={17} />Evidence stays connected to the assessment.</li><li><Check size={17} />Draft edits require renewed review.</li><li><Check size={17} />Contact restrictions remain separate from fit.</li></ul><a href="#example" onClick={openExample} className="landing-text-link">Try it out<ArrowUpRight size={17} /></a></div></section>
      <section id="get-started" className="landing-start-section landing-section" aria-labelledby="start-title"><div className="landing-section-heading"><span className="landing-section-index">04 / Start with one workflow</span><h2 id="start-title">Bring an enquiry.<br />Build understanding.</h2><p>Use a Sandbox workspace to explore the application, or record your interest in a supervised pilot.</p></div><div className="landing-start-grid"><article><span className="landing-start-symbol"><Layers3 size={29} /></span><div><h3>Explore in Sandbox</h3><p>Create a workspace, define your business criteria and try the existing data workflow. Sandbox does not deliver real messages.</p><a href="/register" className="landing-button landing-button-outline">Get started<ArrowUpRight size={16} /></a><a href="/app" className="landing-text-link landing-workspace-link">Already have a workspace? Open it<ArrowUpRight size={14} /></a></div></article><article><span className="landing-start-symbol"><Quote size={29} /></span><div><h3>Shape a focused pilot</h3><p>Tell us which enquiry problem matters in your business. Customer scope, channel and operating requirements need to be agreed before live use.</p><a href="#pilot" className="landing-button landing-button-outline">Share your workflow<ArrowUpRight size={16} /></a></div></article></div></section>
      <section className="landing-faq-section landing-section" aria-labelledby="questions-title"><div><span className="landing-section-index">A few practical questions</span><h2 id="questions-title">Clear expectations,<br />from the start.</h2></div><div className="landing-faq-list">{questions.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={19} /></summary><p>{answer}</p></details>)}</div></section>
      <section id="pilot" className="landing-pilot-section landing-section" aria-labelledby="pilot-title"><div className="landing-pilot-copy"><span className="landing-section-index">A focused next step</span><h2 id="pilot-title">What gets lost<br />between the enquiry<br /><em>and the follow-up?</em></h2><p>Tell us about the work behind the problem. A useful pilot starts with a specific workflow and a clear way to judge progress.</p><div><LockKeyhole size={19} /><span>Your details are stored for pilot-interest review. Keep customer data out of it.</span></div></div><PilotRequestForm /></section>
      <section className="landing-section landing-contact-section" aria-labelledby="contact-title"><div><span className="landing-section-index">Let's talk</span><h2 id="contact-title">See what a clearer<br />next step looks like.</h2><p>Want a guided walkthrough, or have a question about your workflow? Start a conversation.</p></div><div className="landing-hero-actions"><a href="#pilot" className="landing-button landing-button-dark">Book a demo<ArrowUpRight size={18} /></a><a href="#pilot" className="landing-button landing-button-outline">Reach out<ArrowUpRight size={18} /></a></div></section>
    </main>
    <footer className="landing-footer"><div><a href="/" className="landing-footer-brand"><BrandMark className="landing-footer-mark" />Relay</a><p>AI Lead Intelligence &amp; Outbound Automation</p></div><div><a href="#example" onClick={openExample}>Try it out</a><a href="/login">Sign in</a><a href="/product-information">Privacy and support</a><a href="#pilot">Book a demo</a><a href="#pilot">Reach out</a></div><p>Product preview. Live-channel and customer acceptance remain open.<br />No invented customer results. No messages sent by the example.</p></footer>
  </div>;
}
function HeroVisual() {
  return <div className="landing-hero-visual" aria-label="Synthetic enquiry preview"><div className="landing-visual-top"><span><span className="landing-visual-dot" />THE NEXT MOVE</span><span>Synthetic preview</span></div><div className="landing-orbit" aria-hidden="true"><svg viewBox="0 0 520 510" fill="none"><path d="M72 106C220 16 463 58 433 210S102 203 93 352s282 188 362 75" /><path d="M83 116C182 68 420 87 405 203S104 228 117 356s233 127 321 60" /></svg></div><div className="landing-visual-source"><div><span className="landing-visual-avatar">MS</span><span><strong>Mira Shah</strong><small>Sample enquiry · Form Studio</small></span><ArrowUpRight size={17} /></div><p>“We need <mark>12 workstations</mark> for our <mark>Bengaluru studio.</mark>”</p><span className="landing-source-tag"><FileText size={12} />Original context attached</span></div><div className="landing-visual-fact"><span><Check size={13} />Interest match</span><strong>Workstations</strong><span className="landing-visual-fact-line" /></div><div className="landing-visual-budget"><span>?</span><div><strong>Budget unknown</strong><small>A gap to clarify.</small></div></div><div className="landing-visual-decision"><div><ShieldCheck size={17} /><span>NEXT BEST ACTION</span><span>01</span></div><h3>Ask the useful question.</h3><p>Clarify the budget before recommending options.</p><div><span>Human review required</span><ArrowUpRight size={18} /></div></div><div className="landing-visual-bottom"><span className="landing-visual-status" />Explained priority. A reviewed next step.</div></div>;
}
