import { useState } from "react";
import { ArrowRight, ArrowUpRight, Check, ChevronLeft, CircleHelp, Clock3, FileText, LockKeyhole, Quote, RotateCcw, ShieldCheck } from "lucide-react";
import { DEMO_RECORDS, DEMO_STEPS, demoFor, type DemoReply } from "./demo-fixtures";

export default function LandingDemo() {
  const [state, setState] = useState(() => demoFor()), [announcement, announce] = useState("Choose an example enquiry to begin.");
  const record = DEMO_RECORDS.find(item => item.id === state.recordId)!;
  const restricted = record.restricted || state.reply === "OPT_OUT", fact = record.facts[state.fact];
  const actionName = state.action === "ASK" ? "Ask for a missing detail" : state.action === "FOLLOW_UP" ? "Review a follow-up" : "Do not contact";
  function select(id: string) { setState(demoFor(id)); announce("Example changed. Draft, review, response and outcome reset."); }
  function step(value: number) { setState(current => ({ ...current, step: value })); announce("Step " + (value + 1) + ": " + DEMO_STEPS[value]); }
  function edit(key: "subject" | "draft", value: string) { setState(current => ({ ...current, [key]: value, revision: current.revision + 1, reviewedRevision: null, simulated: false, reply: null, outcome: null })); announce("Example draft changed. Review the new revision before simulating an action."); }
  function reply(value: DemoReply) { setState(current => ({ ...current, reply: value, outcome: null })); announce(value === "OPT_OUT" ? "Synthetic opt-out recorded. Further outreach is blocked." : value === "QUESTION" ? "Synthetic question recorded. A human response is the next step." : "No response recorded. No outcome is inferred."); }
  return <div className="demo-workspace" aria-label="Interactive synthetic product example">
    <div className="demo-toolbar"><div><span className="demo-beacon" aria-hidden="true" /><strong>Example workspace</strong><span className="demo-toolbar-detail">Fictional furniture studio · Sep 2026</span></div><button type="button" onClick={() => { setState(demoFor()); announce("Example reset to the first enquiry. Nothing was sent or saved."); }} className="demo-quiet"><RotateCcw size={14} />Reset example</button></div>
    <div className="demo-disclosure"><ShieldCheck size={15} /><span>Interactive example — synthetic data. No messages are sent.</span></div>
    <div className="demo-mobile-record"><label htmlFor="demo-record">Sample enquiry</label><select id="demo-record" value={record.id} onChange={event => select(event.target.value)}>{DEMO_RECORDS.map(item => <option value={item.id} key={item.id}>{item.name} · {item.restricted ? "Contact restricted" : item.fit}</option>)}</select></div>
    <ol className="demo-step-nav" aria-label="Example steps">{DEMO_STEPS.map((label, index) => <li key={label}><button type="button" aria-current={state.step === index ? "step" : undefined} className={state.step === index ? "is-selected" : ""} onClick={() => step(index)}><span>{String(index + 1).padStart(2, "0")}</span>{label}</button></li>)}</ol>
    <div className="demo-body">
      <aside className="demo-rail" aria-label="Sample enquiries"><p className="demo-overline">Your existing enquiries</p>{DEMO_RECORDS.map(item => <button type="button" key={item.id} aria-pressed={item.id === record.id} onClick={() => select(item.id)} className={item.id === record.id ? "demo-record is-selected" : "demo-record"}><span className="demo-avatar">{item.initials}</span><span><strong>{item.name}</strong><small>{item.company}</small><em className={item.restricted ? "demo-restricted-text" : ""}>{item.restricted ? "Do not contact" : item.id === "mira" ? "Budget unknown" : "Follow-up requested"}</em></span><ArrowUpRight size={13} /></button>)}<div className="demo-rail-note"><FileText size={17} /><p>Start with the data you already have.</p><span>Three fictional records. One shared workflow.</span></div></aside>
      <div className="demo-canvas" key={record.id + ":" + state.step}>
        <div className="demo-canvas-heading"><span className="demo-overline">{DEMO_STEPS[state.step]} / {record.name}</span><span className="demo-version">Example v1</span></div>
        {state.step === 0 && <section aria-label="Example source"><h3>{record.title}</h3><p className="demo-intro">Read the original enquiry before interpreting it.</p><div className="demo-source"><div><span><FileText size={14} />{record.source}</span><time>{record.date}</time></div><blockquote><Quote size={21} aria-hidden="true" />{record.quote}</blockquote><p>{record.id === "mira" ? "Country field: India. Budget field: empty." : record.id === "arjun" ? "Country field: India. Follow-up date explicitly recorded." : "Latest stop reply is retained alongside the earlier enquiry."}</p></div><div className="demo-inline-note"><CircleHelp size={16} /><p>These are source statements, not independently verified customer facts.</p></div></section>}
        {state.step === 1 && <section aria-label="Example intelligence"><h3>Open the reason. See the source.</h3><p className="demo-intro">The sample business offers workstations in Bengaluru with a minimum budget of INR 200,000.</p><div className="demo-fact-tabs" aria-label="Inspect a sample criterion">{record.facts.map((item, index) => <button key={item.label} type="button" aria-pressed={state.fact === index} className={state.fact === index ? "is-selected" : ""} onClick={() => { setState(current => ({ ...current, fact: index })); announce(item.label + " evidence opened."); }}>{item.label}{item.outcome === "UNKNOWN" ? <CircleHelp size={14} /> : <Check size={14} />}</button>)}</div><div className="demo-evidence"><div className="demo-evidence-value"><span>{fact.label}</span><strong>{fact.value}</strong><em className={fact.outcome === "UNKNOWN" ? "is-unknown" : ""}>{fact.outcome === "UNKNOWN" ? "Unknown" : fact.label === "Contact" ? "Stop request recorded" : "Supported by this source"}</em></div>{fact.excerpt ? <blockquote>“<mark>{fact.excerpt}</mark>”</blockquote> : <div className="demo-empty-evidence"><CircleHelp size={22} /><p>No budget statement in this source.</p></div>}<p>{fact.explanation}</p></div><p className="demo-bottom-note">Fit, data completeness and contact permission are separate decisions.</p></section>}
        {state.step === 2 && <section aria-label="Example decision"><h3>Choose the next useful move.</h3><p className="demo-intro">{record.note}</p><div className="demo-decisions">{([ ["ASK", "Ask for missing detail", "Clarify what the source does not establish."], ["FOLLOW_UP", "Follow up as requested", "Review an action against the recorded request."], ["STOP", "Do not contact", "Keep the evidence and leave outreach stopped."] ] as const).map(([value, title, text]) => <button type="button" key={value} disabled={restricted && value !== "STOP" || value === "FOLLOW_UP" && record.id !== "arjun"} aria-pressed={(restricted ? "STOP" : state.action) === value} className={(restricted ? "STOP" : state.action) === value ? "is-selected" : ""} onClick={() => { setState(current => ({ ...current, action: value, reviewedRevision: null, simulated: false, reply: record.restricted ? "OPT_OUT" : null, outcome: null })); announce(title + " selected for this example."); }}><span className="demo-choice-dot" /><span><strong>{title}</strong><small>{text}</small></span>{value === "STOP" ? <LockKeyhole size={16} /> : <ArrowUpRight size={16} />}</button>)}</div>{restricted && <p className="demo-stop-note"><LockKeyhole size={16} />The recorded opt-out blocks contact, even when business criteria match.</p>}</section>}
        {state.step === 3 && <section aria-label="Example exact review"><h3>{restricted || state.action === "STOP" ? "Keep the stop in place." : "Your review is part of the workflow."}</h3>{restricted || state.action === "STOP" ? <div className="demo-stopped"><LockKeyhole size={32} /><strong>No contact action available</strong><p>{restricted ? "The explicit opt-out remains authoritative in this example." : "You selected Do not contact. No draft is advanced."}</p></div> : <><div className="demo-recipient"><span>To</span><strong>{record.email}</strong><span>Example revision {state.revision}</span></div><label className="demo-field">Example subject<input aria-label="Example subject" value={state.subject} maxLength={200} onChange={event => edit("subject", event.target.value)} /></label><label className="demo-field">Example message<textarea aria-label="Example message" rows={6} value={state.draft} maxLength={2000} onChange={event => edit("draft", event.target.value)} /></label><p className="demo-review-state">{state.reviewedRevision === state.revision ? <><Check size={15} />Example revision {state.revision} reviewed</> : <><ShieldCheck size={15} />Review required for this exact example revision</>}</p><div className="demo-review-buttons"><button type="button" className="demo-secondary" disabled={!state.subject.trim() || !state.draft.trim() || state.reviewedRevision === state.revision} onClick={() => { setState(current => ({ ...current, reviewedRevision: current.revision })); announce("Example revision reviewed. Editing will require another review."); }}>Mark example revision reviewed</button><button type="button" className="demo-primary" disabled={state.reviewedRevision !== state.revision || !state.subject.trim() || !state.draft.trim()} onClick={() => { setState(current => ({ ...current, simulated: true, step: 4 })); announce("Reviewed action simulated locally. No message was sent."); }}>Simulate reviewed action<ArrowRight size={15} /></button></div><p className="demo-bottom-note">This draft is illustrative. In the product, a reviewer checks the exact recipient, sender, content and current contact restrictions.</p></>}</section>}
        {state.step === 4 && <section aria-label="Example response"><h3>The response changes the next step.</h3><p className="demo-intro">{record.restricted ? "This record already contains an explicit stop. It remains restricted." : state.simulated ? "Choose what happens in this synthetic story. No customer or provider is involved." : "Review and simulate the example action first to explore possible responses."}</p><div className="demo-response-options">{([ ["QUESTION", "A question", "Can we discuss layout options?"], ["NO_RESPONSE", "No response", "No reply has been recorded."], ["OPT_OUT", "An opt-out", "Please stop emailing me."] ] as const).map(([value, label, text]) => <button type="button" key={value} disabled={!state.simulated || record.restricted || state.reply === "OPT_OUT"} className={state.reply === value ? "is-selected" : ""} aria-pressed={state.reply === value} onClick={() => reply(value)}><strong>{label}</strong><span>“{text}”</span></button>)}</div>{state.reply && <div className={state.reply === "OPT_OUT" ? "demo-response-result is-stop" : "demo-response-result"}>{state.reply === "OPT_OUT" ? <LockKeyhole size={21} /> : state.reply === "QUESTION" ? <CircleHelp size={21} /> : <Clock3 size={21} />}<div><strong>{state.reply === "OPT_OUT" ? "Further outreach blocked" : state.reply === "QUESTION" ? "A human response is needed" : "No outcome recorded"}</strong><p>{state.reply === "OPT_OUT" ? "Keep the stop restriction and cancel future contact in this example. Reset to explore another branch." : state.reply === "QUESTION" ? "The customer's question becomes the next piece of work for an operator." : "Keep the enquiry open for review. Silence does not establish interest, consent or a sale."}</p></div></div>}</section>}
        {state.step === 5 && <section aria-label="Example outcome"><h3>Keep progress tied to a real event.</h3><p className="demo-intro">This final step previews operator-recorded outcomes. Select only what the synthetic story supports.</p><div className="demo-outcomes">{([ ["MEETING_REQUESTED", "Meeting requested"], ["FOLLOW_UP_RECORDED", "Follow-up recorded"], ["CLOSED", "Closed enquiry"] ] as const).map(([value, label]) => <button type="button" key={value} disabled={value !== "CLOSED" && (restricted || !state.simulated || state.reply !== "QUESTION")} aria-pressed={state.outcome === value} className={state.outcome === value ? "is-selected" : ""} onClick={() => { setState(current => ({ ...current, outcome: value })); announce("Sample outcome recorded by a human. No application data was changed."); }}>{label}<ArrowUpRight size={15} /></button>)}</div>{state.outcome ? <div className="demo-outcome-record"><span className="demo-overline">Sample outcome · recorded by a human</span><strong>{state.outcome === "MEETING_REQUESTED" ? "Meeting requested" : state.outcome === "FOLLOW_UP_RECORDED" ? "Follow-up recorded" : "Enquiry closed"}</strong><p>{restricted ? "Contact remains restricted." : state.outcome === "CLOSED" ? "No further action is assumed." : "Next: the operator confirms the details and records what happens."}</p><small>Example only. A recorded request is not revenue.</small></div> : <p className="demo-bottom-note">No outcome selected. Nothing is inferred from message activity.</p>}</section>}
        <div className="demo-stage-controls"><button type="button" className="demo-quiet" disabled={state.step === 0} onClick={() => step(state.step - 1)}><ChevronLeft size={15} />Back</button><span>Step {state.step + 1} of {DEMO_STEPS.length}</span>{state.step < DEMO_STEPS.length - 1 ? <button type="button" className="demo-quiet" onClick={() => step(state.step + 1)}>Next: {DEMO_STEPS[state.step + 1]}<ArrowRight size={15} /></button> : <a className="demo-quiet" href="#get-started">Explore getting started<ArrowUpRight size={15} /></a>}</div>
      </div>
      <aside className="demo-next" aria-label="Example next step"><span className="demo-overline">A decision you can inspect</span><div className="demo-signal-ring" aria-hidden="true"><ShieldCheck size={29} /></div><p className="demo-next-title">{restricted ? "Do not contact" : state.reply === "QUESTION" ? "Answer the question" : state.outcome === "CLOSED" ? "Enquiry closed" : actionName}</p><dl><div><dt>Business fit</dt><dd>{record.fit}</dd></div><div><dt>Contact</dt><dd className={restricted ? "demo-restricted-text" : ""}>{restricted ? "Restricted" : "Independent review required"}</dd></div><div><dt>Automation</dt><dd>Simulation only</dd></div></dl><p>{restricted ? "A strong fit never overrides a stop request." : "The reason stays visible. The final review stays with a person."}</p></aside>
    </div>
    <div className="demo-footer"><span>Product preview · deterministic sample data</span><span>Source → Intelligence → Review → Response</span></div><p className="landing-sr-only" role="status" aria-live="polite" aria-atomic="true">{announcement}</p>
  </div>;
}
