import {BrandMark} from "@/components/brand-mark";
import {useEffect,useState} from "react";
import {api,ApiError} from "@/lib/api";
type State={security_revision:number;recovery:{generation:number;usable_count:number;expires_at:string|null};sessions:{public_id:string;created_at:string;expires_at:string;current:boolean}[];history:{changes:{id:string;revision:number;operation:string;created_at:string}[]}};
const button="rounded-lg border border-line px-3 py-2 text-sm disabled:opacity-50",field="mt-1 w-full rounded-lg border border-line bg-surface p-2 text-sm";
function issue(error:unknown){return error instanceof ApiError&&error.body&&typeof error.body==="object"?(error.body as {error?:string}).error||"Security change was rejected.":"The result could not be confirmed. Refresh security history before trying again; recovery codes are shown only on the original successful response.";}
export function AccountSecurity(){const [state,setState]=useState<State|null>(null),[current,setCurrent]=useState(""),[next,setNext]=useState(""),[codes,setCodes]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[uncertain,setUncertain]=useState(false);
 async function refresh(){try{setState(await api.get<State>("/auth/security"));setUncertain(false);}catch(e){setError(issue(e));}}
 useEffect(()=>{void refresh();},[]);
 async function change(path:string,password=false){if(!state||busy||uncertain)return;setBusy(true);setError("");setCodes([]);try{const result=await api.post<{sign_in_required:boolean;recovery_codes?:string[]}>("/auth/security/"+path,{expected_security_revision:state.security_revision,current_password:current,...(password?{new_password:next}:{})});setCurrent("");setNext("");if(result.sign_in_required){window.location.assign("/login?returnTo="+encodeURIComponent("/settings?tab=security"));return;}setCodes(result.recovery_codes||[]);setNotice("Security change recorded.");await refresh();}catch(e){setError(issue(e));setUncertain(true);}finally{setBusy(false);}}
 return <section aria-label="Account security" className="max-w-3xl space-y-5"><h2 className="text-xl font-semibold">Account security</h2><p className="text-sm text-muted">Manage your password, offline recovery codes and signed-in sessions. Security changes require your current password.</p>{error&&<p role="alert" className="text-sm text-danger">{error}</p>}{notice&&<p role="status" className="text-sm">{notice}</p>}<button type="button" className={button} disabled={busy} onClick={()=>void refresh()}>Refresh security and history</button>
 {state&&<><label className="block text-sm">Current password<input aria-label="Security current password" type="password" autoComplete="current-password" className={field} value={current} onChange={e=>setCurrent(e.target.value)} maxLength={1024} disabled={busy}/></label>
 <div className="rounded-xl border border-line p-4 space-y-3"><h3 className="font-semibold">Change password</h3><label className="block text-sm">New password<input aria-label="Security new password" type="password" autoComplete="new-password" className={field} value={next} onChange={e=>setNext(e.target.value)} minLength={8} maxLength={1024} disabled={busy}/></label><p className="text-xs text-muted">Changing your password signs out every session, including this one. Sign in again with the new password.</p><button type="button" className={button} disabled={busy||uncertain||!current||next.length<8} onClick={()=>void change("password",true)}>Change password and sign out</button></div>
 <div className="rounded-xl border border-line p-4 space-y-3"><h3 className="font-semibold">Offline recovery</h3><p className="text-sm">{state.recovery.usable_count} unused recovery codes.{state.recovery.expires_at?" Expires "+new Date(state.recovery.expires_at).toLocaleDateString()+".":" No recovery codes have been created."}</p><p className="text-xs text-muted">Create and save your codes before you need account recovery. Each code works once. Replacing the set invalidates older codes.</p><button type="button" className={button} disabled={busy||uncertain||!current} onClick={()=>void change("recovery-codes")}>Replace recovery codes</button>{codes.length>0&&<div className="space-y-2 rounded-lg bg-soft p-3"><p className="font-medium">Save these codes offline. They are shown only now.</p><textarea aria-label="New recovery codes" readOnly rows={8} value={codes.join("\n")} className={field}/><button type="button" className={button} onClick={()=>{const url=URL.createObjectURL(new Blob(["AI Lead Intelligence & Outbound Automation recovery codes\nKeep these private. Each code can be used once.\n\n"+codes.join("\n")],{type:"text/plain"}));const a=document.createElement("a");a.href=url;a.download="account-recovery-codes.txt";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download recovery codes</button><button type="button" className={button} onClick={()=>setCodes([])}>I saved my codes; hide them</button></div>}</div>
 <div className="rounded-xl border border-line p-4 space-y-3"><h3 className="font-semibold">Signed-in sessions</h3><p className="text-xs text-muted">Session dates help identify access. No device identity is inferred from them.</p>{state.sessions.map(row=><div key={row.public_id} className="flex flex-wrap items-center justify-between gap-3 border-b border-line py-2 text-sm"><span>{row.current?"This session":"Other session"} - {new Date(row.created_at).toLocaleString()}</span><button type="button" className={button} disabled={busy||uncertain||!current} onClick={()=>void change("sessions/"+row.public_id+"/revoke")}>{row.current?"Sign out this session":"Revoke session"}</button></div>)}<div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={busy||uncertain||!current} onClick={()=>void change("sessions/revoke-others")}>Revoke other sessions</button><button type="button" className={button} disabled={busy||uncertain||!current} onClick={()=>void change("sessions/revoke-all")}>Revoke all sessions</button></div></div>
 <details><summary className="cursor-pointer font-medium">Recent security history</summary><ol className="mt-3 space-y-2 text-sm">{state.history.changes.map(row=><li key={row.id}>Revision {row.revision}: {row.operation.replaceAll("_"," ")} ? {new Date(row.created_at).toLocaleString()}</li>)}</ol></details></>}
 </section>;
}
export function AccountRecoveryPage(){const [email,setEmail]=useState(""),[code,setCode]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(false);
 return <main className="mx-auto w-full max-w-lg self-start px-6 py-12 sm:py-20"><a href="/" aria-label="Relay home" className="mb-10 flex w-fit items-center gap-3"><BrandMark className="h-9 w-9"/><span className="brand-wordmark text-2xl">Relay.</span></a><a href="/login" className="text-brand underline">Back to sign in</a><h1 className="mt-8 font-display text-4xl font-normal tracking-tight">Recover your account</h1><p className="my-4 text-sm text-muted">Use one of the offline recovery codes you saved in Account security. Recovery signs out existing sessions.</p>{done?<p role="status">Password updated. <a href="/login" className="underline">Sign in with your new password.</a></p>:<form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError("");try{await api.post("/auth/recover",{email,recovery_code:code,new_password:password});setCode("");setPassword("");setDone(true);}catch(err){setError(issue(err)+" If the response was interrupted, try signing in with your new password before using another recovery code.");}finally{setBusy(false);}}}><label className="block text-sm">Email<input aria-label="Recovery email" className={field} type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block text-sm">Recovery code<input aria-label="Recovery code" autoComplete="off" className={field} required value={code} onChange={e=>setCode(e.target.value)}/></label><label className="block text-sm">New password<input aria-label="Recovery new password" className={field} type="password" autoComplete="new-password" minLength={8} maxLength={1024} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="text-sm text-danger">{error}</p>}<button className={button} disabled={busy}>Recover and reset password</button></form>}</main>;
}
