import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api, ApiError } from "@/lib/api";
import { useMe } from "@/hooks/use-auth";
import { useWorkspaceStore } from "@/stores/workspace";
import type { AiControls, AiControlsResponse, AiPricing, AiUsageResponse, AiUsageSummary } from "@/types/analysis-jobs";
import { contextFieldClass } from "./context-editor";
import { analysisJobIssue } from "./analysis-jobs";

const button = "rounded-lg border border-line px-3 py-2 text-sm text-brand disabled:opacity-50";
export function AnalysisControls({ customer = false }: { customer?: boolean }) {
  const org = useWorkspaceStore(state => state.currentOrg), { data: me } = useMe(), owner = me?.user.role === "OWNER";
  const query = useQuery({ queryKey: ["ai-controls", org?.id], queryFn: () => api.get<AiControlsResponse>("/ai/controls?organization_id=" + org!.id), enabled: Boolean(org && owner), retry: false, refetchInterval: 10000, refetchIntervalInBackground: false });
  if (!owner || !org) return <p className="text-sm text-muted">A workspace owner can review model usage and change analysis limits.</p>;
  return <section aria-label="AI usage and limits" className="space-y-5"><h2 className="text-lg font-semibold">AI usage and analysis limits</h2><p className="text-sm text-muted">Limits apply to admitted model calls for source summaries and reply interpretation. Application rules and unchanged saved-result reuse do not consume a model call. These controls do not approve or send outbound work.</p>
    {query.isError && <p role="alert" className="text-sm text-warn">AI controls could not be checked. Displayed usage may be outdated; refresh before changing limits.</p>}
    {query.data ? <ControlsEditor customer={customer} key={org.id} state={query.data} organizationId={org.id} uncertain={query.isError} refresh={() => query.refetch().then(result => { if (result.error || !result.data) throw result.error || new Error("Unavailable"); return result.data; })} /> : <p role="status" className="text-sm">{query.isError ? "Saved controls unavailable." : "Loading AI limits..."}</p>}
    <button type="button" className={button} disabled={query.isFetching} onClick={() => void query.refetch()}>Check saved AI limits</button>{!customer && <UsageHistory organizationId={org.id} />}
  </section>;
}
function draftFor(controls: AiControls) { return { revision: controls.revision, paused: controls.paused, daily: String(controls.max_daily_attempts), concurrent: String(controls.max_in_flight), pricing: controls.pricing.map(row => ({ ...row })), reason: "" }; }
function ControlsEditor({ state, organizationId, uncertain, refresh, customer }: { customer: boolean; state: AiControlsResponse; organizationId: string; uncertain: boolean; refresh: () => Promise<AiControlsResponse> }) {
  const client = useQueryClient(), [draft, setDraft] = useState(() => draftFor(state.controls));
  const [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [saved, setSaved] = useState(false), [historyOpen, setHistoryOpen] = useState(false);
  const stale = draft.revision !== state.controls.revision;
  const valid = /^\d+$/.test(draft.daily) && Number(draft.daily) >= 1 && Number(draft.daily) <= 10000 && /^\d+$/.test(draft.concurrent) && Number(draft.concurrent) >= 1 && Number(draft.concurrent) <= 100 && draft.pricing.length <= 20 && draft.pricing.every(row => row.provider.trim() && row.model.trim() && rateValid(row.input_usd_per_million) && rateValid(row.output_usd_per_million)) && new Set(draft.pricing.map(row => row.provider.trim() + "\n" + row.model.trim())).size === draft.pricing.length;
  async function save(event: React.FormEvent) {
    event.preventDefault(); if (busy || stale || uncertain || !valid || !draft.reason.trim()) return;
    setBusy(true); setError(null); setSaved(false);
    try { const next = await api.put<AiControlsResponse>("/ai/controls", { organization_id: organizationId, expected_revision: draft.revision, reason: draft.reason, paused: draft.paused, max_daily_attempts: Number(draft.daily), max_in_flight: Number(draft.concurrent), pricing: draft.pricing }); client.setQueryData(["ai-controls", organizationId], next); setDraft(draftFor(next.controls)); setSaved(true); void client.invalidateQueries({ queryKey: ["ai-usage"] }); void client.invalidateQueries({ queryKey: ["ai-controls-history"] }); }
    catch (failure) { setError(failure instanceof ApiError && failure.status === 409 ? "AI limits changed in another session. Your draft is retained; check the latest saved revision before replacing it." : "AI limits could not be saved. Your draft remains; check saved state before retrying."); void client.invalidateQueries({ queryKey: ["ai-controls", organizationId] }); }
    finally { setBusy(false); }
  }
  function setRate(index: number, field: keyof AiPricing, value: string) { setDraft(previous => ({ ...previous, pricing: previous.pricing.map((row, position) => position === index ? { ...row, [field]: value } : row) })); }
  return <>{customer ? <section aria-label="Current AI usage" className="rounded-xl border border-line p-4"><p className="font-semibold">AI assistance usage today</p><p className="mt-2 text-sm">{state.usage.admitted_attempts} of {state.usage.limits.max_daily_attempts} requests used.</p><p className="mt-2 text-xs text-muted">Daily limits reset at midnight UTC. Saved-result reuse and application rules do not use an AI request.</p></section> : <UsageSummary summary={state.usage} />}<form onSubmit={save} aria-label="AI limits editor" className="space-y-4 rounded-xl border border-line p-4">
    <div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">Owner controls</h3><span className="text-xs text-muted">Saved revision {state.controls.revision}; editing revision {draft.revision}</span></div>
    <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={draft.paused} onChange={event => setDraft({ ...draft, paused: event.target.checked })} />{customer ? "Pause new AI assistance" : "Pause new model invocations"}</label><p className="text-xs text-muted">A pause blocks new admissions. It cannot recall already admitted work or refund its usage. Direct stop handling and application rules remain available.</p>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">{customer ? "AI requests per day (UTC)" : "Model calls per UTC day"}<input className={contextFieldClass} inputMode="numeric" maxLength={5} value={draft.daily} onChange={event => setDraft({ ...draft, daily: event.target.value })} /></label><label className="text-sm">{customer ? "Simultaneous AI requests" : "Logical in-flight model limit"}<input className={contextFieldClass} inputMode="numeric" maxLength={3} value={draft.concurrent} onChange={event => setDraft({ ...draft, concurrent: event.target.value })} /></label></div>
    <p className="text-xs text-muted">Daily limit: 1–10,000. Logical in-flight limit: 1–100. A request may continue processing after a local timeout. Changing limits does not erase prior admissions.</p>
    {!customer && <fieldset className="space-y-3 border-t border-line pt-3"><legend className="text-sm font-semibold">Optional cost estimation rates</legend><p className="text-xs text-muted">Enter your own exact USD rates per million tokens for a specific requested provider and model. Estimates use reported token counts. No rates are fetched or assumed; these are neither invoices nor hard monetary spending limits.</p>
      {draft.pricing.length === 0 && <p className="text-sm text-muted">No estimation rates configured. Model cost remains unknown.</p>}
      {draft.pricing.map((row, index) => <div key={index} role="group" aria-label={"Estimation rate " + (index + 1)} className="space-y-3 rounded-lg border border-line p-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Provider identifier<input className={contextFieldClass} maxLength={100} value={row.provider} onChange={event => setRate(index, "provider", event.target.value)} /></label><label className="text-sm">Requested model identifier<input className={contextFieldClass} maxLength={200} value={row.model} onChange={event => setRate(index, "model", event.target.value)} /></label><label className="text-sm">Input USD per million tokens<input className={contextFieldClass} inputMode="decimal" maxLength={14} value={row.input_usd_per_million} onChange={event => setRate(index, "input_usd_per_million", event.target.value)} /></label><label className="text-sm">Output USD per million tokens<input className={contextFieldClass} inputMode="decimal" maxLength={14} value={row.output_usd_per_million} onChange={event => setRate(index, "output_usd_per_million", event.target.value)} /></label></div><button type="button" className={button} onClick={() => setDraft(previous => ({ ...previous, pricing: previous.pricing.filter((_, position) => position !== index) }))}>Remove estimation rate {index + 1}</button></div>)}
      <button type="button" className={button} disabled={draft.pricing.length >= 20} onClick={() => setDraft(previous => ({ ...previous, pricing: [...previous.pricing, { provider: "", model: "", input_usd_per_million: "", output_usd_per_million: "" }] }))}>Add estimation rate</button><p className="text-xs text-muted">At most 20 unique provider/model pairs; rates from 0 to 1,000,000 with up to six decimal places. Zero is an explicit owner rate, not evidence that a model is free.</p>
    </fieldset>}
    <label className="block text-sm">Reason for changing AI limits<textarea required maxLength={2000} className={contextFieldClass} value={draft.reason} onChange={event => setDraft({ ...draft, reason: event.target.value })} /></label>
    {(error || stale) && <p role="alert" className="text-sm text-warn">{error || "Saved controls changed. Your draft remains unchanged; review the latest revision before saving."}</p>}{!valid && <p className="text-sm text-warn">Review the numeric limits and complete each unique estimation rate with valid exact decimals.</p>}{saved && <p role="status" className="text-sm text-ok">AI limits saved with revision history.</p>}
    <div className="flex flex-wrap gap-2"><button type="submit" className={button} disabled={busy || uncertain || stale || !valid || !draft.reason.trim()}>{busy ? "Saving AI limits..." : "Save AI limits"}</button><button type="button" className={button} disabled={busy} onClick={async () => { setBusy(true); try { setDraft(draftFor((await refresh()).controls)); setError(null); setSaved(false); } catch { setError("Latest controls could not be loaded. Your draft is retained."); } finally { setBusy(false); } }}>Replace draft with latest saved limits</button></div>
  </form>{!customer && <button type="button" className={button} onClick={() => setHistoryOpen(value => !value)}>{historyOpen ? "Hide AI limits history" : "View AI limits history"}</button>}{historyOpen && <ControlsHistory organizationId={organizationId} />}</>;
}
function UsageSummary({ summary }: { summary: AiUsageSummary }) {
  return <section aria-label="Current AI usage" className="space-y-3 rounded-xl border border-line bg-surface p-4"><h3 className="font-semibold">Current UTC day: {summary.budget_day}</h3>
    <div className="grid gap-3 sm:grid-cols-3"><div><p className="text-lg font-semibold">{summary.admitted_attempts} / {summary.limits.max_daily_attempts}</p><p className="text-xs text-muted">Model call admissions</p></div><div><p className="text-lg font-semibold">{summary.in_flight} / {summary.limits.max_in_flight}</p><p className="text-xs text-muted">Logical in-flight slots</p></div><div><p className="text-lg font-semibold">{summary.cost.estimated_usd === null ? "Unknown" : "USD " + summary.cost.estimated_usd}</p><p className="text-xs text-muted">Estimated subtotal for {summary.cost.estimated_attempts} reported attempts</p></div></div>
    {summary.hold_code && <p className="text-sm text-warn">{analysisJobIssue(summary.hold_code)}</p>}
    <p className="text-sm text-muted">{summary.provider_reported_attempts} attempts have reported usage; {summary.unknown_usage_attempts} have unknown usage. Cost is unknown for {summary.cost.unknown_attempts} attempts. Missing usage or cost is never counted as zero.</p>
    <p className="text-xs text-muted">Known token subtotals: input {known(summary.input_tokens_known_total)}, output {known(summary.output_tokens_known_total)}, total {known(summary.total_tokens_known_total)}. Estimates use owner rates and provider-reported tokens; they are not a provider invoice or a monetary cap.</p><p className="text-xs text-muted">Next UTC reset: {when(summary.next_reset_at)}. Rejected output, timeout and cancellation still consume an admitted call; retry and limit edits do not refund it.</p>
  </section>;
}
function ControlsHistory({ organizationId }: { organizationId: string }) {
  const [before, setBefore] = useState<number | null>(null);
  const query = useQuery({ queryKey: ["ai-controls-history", organizationId, before], queryFn: () => api.get<AiControlsResponse>("/ai/controls?organization_id=" + organizationId + "&limit=20" + (before === null ? "" : "&before_revision=" + before)), retry: false });
  return <section aria-label="AI limits history" className="space-y-3">{query.isError && <p role="alert">AI limits history could not be loaded.</p>}{query.data?.history.items.map(item => <article key={item.revision} className="space-y-1 rounded-lg border border-line p-3 text-sm"><p className="font-medium">Revision {item.revision} · {when(item.created_at)}</p><p>{item.reason}</p><p className="text-xs text-muted">{item.controls.paused ? "New model calls paused" : "New model calls enabled"}; daily {item.controls.max_daily_attempts}; logical in-flight {item.controls.max_in_flight}; {item.controls.pricing.length} estimation rates.</p><details><summary className="cursor-pointer text-xs text-brand">Recorded estimation rates</summary>{item.controls.pricing.map((rate, index) => <p className="mt-1 break-words text-xs" key={index}>{rate.provider} / {rate.model}: input USD {rate.input_usd_per_million}; output USD {rate.output_usd_per_million} per million tokens.</p>)}</details></article>)}<div className="flex gap-2"><button type="button" className={button} disabled={before === null || query.isFetching} onClick={() => setBefore(null)}>Latest limit changes</button><button type="button" className={button} disabled={!query.data?.history.has_more || query.isFetching || query.data.history.next_before_revision === null} onClick={() => setBefore(query.data!.history.next_before_revision)}>Older limit changes</button></div></section>;
}
function UsageHistory({ organizationId }: { organizationId: string }) {
  const [cursors, setCursors] = useState<(string | null)[]>([null]), before = cursors.at(-1);
  const query = useQuery({ queryKey: ["ai-usage", organizationId, before], queryFn: () => api.get<AiUsageResponse>("/ai/usage?organization_id=" + organizationId + "&limit=25" + (before ? "&before_attempt_id=" + encodeURIComponent(before) : "")), retry: false, refetchInterval: 10000, refetchIntervalInBackground: false });
  return <section aria-label="AI invocation history" className="space-y-3 border-t border-line pt-4"><h3 className="font-semibold">Model invocation history</h3><p className="text-xs text-muted">Current UTC-day metadata only. Client-observed duration is not provider billing time; an unconfirmed outcome does not prove that remote work stopped.</p>{query.isError && <p role="alert">Invocation history could not be checked.</p>}{query.data && <p className="text-sm text-muted">{query.data.items.length} attempts shown for {query.data.summary.budget_day}.</p>}
    {query.data?.items.map(item => <article key={item.id} className="space-y-2 rounded-lg border border-line p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><p className="font-medium">{item.purpose === "SYNTHESIS" ? "Source summary" : item.purpose === "REPLY_CLASSIFICATION" ? "Reply interpretation" : "Recorded model operation"}</p><span className="text-xs">{item.request_state === "ADMITTED" ? "Admitted; awaiting observation" : item.request_state === "UNCONFIRMED" ? "Outcome unconfirmed" : "Outcome recorded"}</span></div><p className="break-words text-xs text-muted">Requested: {item.provider} / {item.requested_model}; returned model: {item.response_model || "Not reported"}.</p><p className="text-xs text-muted">Admitted {when(item.authorized_at)}. Client-observed duration: {item.elapsed_ms === null ? "Unknown" : item.elapsed_ms + " ms"}.</p><p className="text-xs">{item.usage_status === "PROVIDER_REPORTED" ? "Provider-reported tokens: input " + known(item.input_tokens) + ", output " + known(item.output_tokens) + ", total " + known(item.total_tokens) + "." : "Provider token usage unknown."} Estimated cost: {item.cost_estimate_usd === null ? "Unknown" : "USD " + item.cost_estimate_usd}.</p>{item.lead_id && <Link className="text-xs text-brand underline" to={"/leads/" + item.lead_id + "?tab=intelligence"}>Review affected lead</Link>}<details><summary className="cursor-pointer text-xs text-brand">Attempt reference and estimate version</summary><p className="mt-1 break-all text-xs">{item.id}</p><p className="text-xs">Pricing revision: {item.pricing_revision ?? "Not recorded"}. Observed: {when(item.observed_at)}.</p><p className="break-words text-xs">Captured pipeline: {item.pipeline_version || "Not recorded"}; prompt: {item.prompt_version || "Not recorded"}; schema: {item.schema_version || "Not recorded"}.</p></details></article>)}
    <div className="flex gap-2"><button type="button" className={button} disabled={cursors.length === 1 || query.isFetching} onClick={() => setCursors(previous => previous.slice(0, -1))}>Previous usage page</button><button type="button" className={button} disabled={!query.data?.has_more || !query.data.next_before_attempt_id || query.isFetching} onClick={() => setCursors(previous => [...previous, query.data!.next_before_attempt_id])}>Next usage page</button></div>
  </section>;
}
function rateValid(value: string) { const match = /^(\d+)(?:\.(\d{1,6}))?$/.exec(value); return Boolean(match && BigInt(match[1]) * 1000000n + BigInt((match[2] || "").padEnd(6, "0")) <= 1000000000000n); }
function known(value: number | null) { return value === null ? "Unknown" : String(value); }
function when(value: string | null) { return value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString() : "Not recorded"; }
