import { Link, useLocation } from "react-router-dom";
import { useEffect } from "react";
import { budgetInput, type Budget, type BudgetInput, type EnquiryFact, type FactValue, type Location, type Timeline } from "@/types/business-context";
import { attentionLabels, fitFieldLabels, fitStatusLabels, type AttentionPriority, type BusinessFit, type CriterionResult, type FitField } from "@/types/business-fit";
import { CriterionRule } from "./fit-criteria";
export function BusinessFitBadge({ fit }: { fit?: Pick<BusinessFit, "status"> | null }) { return <span className={"inline-block rounded px-2 py-1 text-xs font-medium " + (fit?.status === "MATCHES_CRITERIA" ? "bg-ok-light text-ok" : fit?.status === "NEEDS_REVIEW" ? "bg-warn-light text-warn" : "bg-soft text-muted")}>{fit ? fitStatusLabels[fit.status] : "Business fit unassessed"}</span>; }
export function BusinessFitPanel({ leadId, fit, attention, currentnessError, leadStatus }: { leadId: string; fit?: BusinessFit | null; attention?: AttentionPriority | null; currentnessError: boolean; leadStatus?: string }) {
  const { hash } = useLocation();
  useEffect(() => { if (hash === "#business-fit") document.getElementById("business-fit")?.scrollIntoView({ block: "start" }); }, [hash, leadId]);
  return <section id="business-fit" aria-label="Business fit and priority" className="rounded-xl border border-line bg-surface p-4 space-y-4"><div className="flex flex-wrap justify-between items-center gap-3"><h3 className="font-semibold">Business fit and attention priority</h3><BusinessFitBadge fit={currentnessError ? null : fit} /></div>
    <p className="text-sm text-muted">Fit compares saved enquiry facts with the owner's explicit criteria. Data readiness, a predicted purchase and permission to contact are different questions.</p>
    {currentnessError ? <p role="alert" className="text-sm text-warn">Current business fit could not be confirmed. Check saved state before using a previous result.</p> : !fit ? <p className="text-sm text-muted">No current business-fit assessment is available. Review saved criteria and sources, then explicitly refresh analysis.</p> : <>
      <p className="text-xs text-muted">Business profile and criteria revision {fit.criteria_revision}; assessed {new Date(fit.evaluated_at).toLocaleString()}.</p>
      {fit.status === "NOT_CONFIGURED" && <p className="text-sm text-muted">No active configured criteria were assessed. Descriptive profile text alone does not establish business fit.</p>}
      {attention && <section aria-label="Attention priority" className="rounded-lg bg-soft p-3 space-y-2"><h4 className="text-sm font-semibold">{attentionLabels[attention.band]}</h4><p className="text-sm text-muted">{attention.reason}</p><p className="text-xs text-muted">{attention.preferred_total ? attention.preferred_matches + " of " + attention.preferred_total + " configured preferences have confirmed matches." : "No preferred criteria configured."}</p>{attention.ranking_incomplete && <p className="text-sm text-warn">Assessment coverage incomplete. Some criteria or preferences still need review; unknown values are not failed criteria.</p>}<p className="text-xs text-muted">This is a configured-rule ordering, not a conversion probability or contact instruction.</p></section>}
      {fit.unassessed_profile_criteria && <p className="rounded-lg border border-warn p-3 text-sm text-warn">Descriptive profile criteria still need manual review. They were not silently converted into rules.</p>}
      {fit.criterion_results.length > 0 && <div className="space-y-3">{fit.criterion_results.map(result => <CriterionAssessment key={result.criterion_id} leadId={leadId} result={result} />)}</div>}
      {fit.limitations.length > 0 && <details><summary className="text-sm text-brand cursor-pointer">Assessment limits</summary><ul className="mt-2 list-disc pl-5 space-y-1 text-xs text-muted">{fit.limitations.map((limit, index) => <li key={index}>{limit}</li>)}</ul></details>}
    </>}
    <div className="flex flex-wrap gap-4 text-sm"><Link className="text-brand underline" to="/settings?tab=fit">Review configured fit criteria</Link><Link className="text-brand underline" to={"/leads/" + leadId + "?tab=outbound"}>Review contact policy and outbound work separately</Link></div>
    <p className="text-xs text-muted">{leadStatus === "OPTED_OUT" ? "This lead has a recorded opt-out. " : leadStatus === "SUPPRESSED" ? "This lead has a recorded suppression. " : ""}A fit match never clears a restriction, creates permission or approves a message. Review the exact recipient, channel and work in the outbound flow.</p>
  </section>;
}
const outcomeLabels = { MATCH: "Criterion matched", NOT_MATCH: "Criterion not matched", UNKNOWN: "Unknown - more information needed", NEEDS_REVIEW: "Source review required" };
export function fitReason(code: string) { const reasons: Record<string, string> = {
  EXACT_ALIAS_MATCH: "The complete recorded value matches an approved alias.", EXPLICIT_EXCLUSION: "The recorded value matches an explicit exclusion.", UNMAPPED_INTEREST: "The recorded interest is not an approved whole-value alias; its meaning was not guessed.", LOCATION_MATCH: "The recorded country and locality match an approved area.", COUNTRY_OUTSIDE_AREAS: "The recorded country is outside the configured areas.", UNMAPPED_LOCALITY: "The recorded locality is not an approved locality or alias.", MISSING_COUNTRY: "The enquiry's country is missing; phone and currency were not used to infer it.", BUDGET_MEETS_MINIMUM: "The recorded budget range meets the configured minimum.", BUDGET_BELOW_MINIMUM: "The recorded maximum budget is below the configured minimum.", BUDGET_STRADDLES_MINIMUM: "The recorded budget range crosses the minimum; fit remains unknown.", CURRENCY_MISMATCH: "The recorded currency differs from the criterion; no currency conversion was performed.", TARGET_DATE_IN_WINDOW: "The recorded target date is within the inclusive date window.", TARGET_DATE_OUTSIDE_WINDOW: "The recorded target date is outside the configured date window.", MISSING_TARGET_DATE: "An explicit target date is missing; timing prose was not interpreted.", UNKNOWN_FACT: "No value is established for this criterion.", STALE: "The source observation is older than the freshness policy window.", AGE_UNKNOWN: "The observation time is unknown.", INFERRED_FACT: "An inference cannot establish a criterion match.", CONFLICTED_FACT: "Conflicting accounts need review; no alternative was selected.", FUTURE_DATED: "The observation was later than its recording time.", INVALID_TIME: "The recorded timestamp is invalid."
}; return reasons[code] || code.replaceAll("_", " ").toLowerCase(); }
function CriterionAssessment({ leadId, result }: { leadId: string; result: CriterionResult }) { const source = result.evidence; return <article aria-label={fitFieldLabels[result.criterion_id] + " fit assessment"} className="rounded-lg border border-line p-3 space-y-3"><div className="flex flex-wrap gap-2 justify-between"><h4 className="font-medium text-sm">{fitFieldLabels[result.criterion_id]} - {result.requirement === "REQUIRED" ? "Required" : "Preferred"}</h4><span className={"text-xs " + (result.outcome === "MATCH" ? "text-ok" : "text-warn")}>{outcomeLabels[result.outcome]}</span></div><div className="text-xs text-muted"><CriterionRule field={result.criterion_id} rule={result.rule} /></div><ul className="list-disc pl-5 text-sm text-muted">{result.reason_codes.map((code, index) => <li key={index}>{fitReason(code)}</li>)}</ul><details><summary className="cursor-pointer text-sm text-brand">Exact source used for this criterion</summary><div className="mt-3 space-y-2"><SourceFact field={result.criterion_id} fact={source.fact} /><p className="text-xs text-muted">Freshness assessment: {source.freshness.freshness.replaceAll("_", " ").toLowerCase()}; {source.freshness.usable ? "usable within the assessment" : "not usable as an established current assertion"}.</p></div></details>{result.missing_fields.length > 0 && <p className="text-xs text-muted">Information to review: {result.missing_fields.map(field => field.replaceAll("_", " ").replaceAll(".", " / ")).join(", ")}.</p>}<Link className="inline-block text-sm text-brand underline" to={"/leads/" + leadId + "?tab=enquiry#enquiry-" + result.criterion_id}>Review {fitFieldLabels[result.criterion_id].toLowerCase()} and source history</Link></article>; }
function sourceValue(field: FitField, value: FactValue) { if (field === "budget") { const budget = budgetInput(value as Budget | BudgetInput); return budget.currency + " " + budget.minimum + (budget.minimum === budget.maximum ? " (exact)" : " to " + budget.maximum + " (range)"); } if (field === "location") { const location = value as Location; return location.locality + ", " + (location.country_code || "country unknown"); } if (field === "timeline") { const timeline = value as Timeline; return timeline.description + "; target date: " + (timeline.target_date || "unknown"); } return String(value); }
function SourceFact({ field, fact }: { field: FitField; fact: EnquiryFact }) { if (fact.state === "UNKNOWN") return <p className="text-sm text-muted">Unknown: no recorded value or supporting source is asserted.</p>; const entries = fact.state === "CONFLICTED" ? fact.alternatives : [fact]; return <div className="space-y-3">{fact.state === "CONFLICTED" && <p className="text-sm text-warn">Conflicting accounts; none selected.</p>}{entries.map((entry, index) => <div key={index} className="border-l-2 border-line pl-3 space-y-1 break-words"><p className="text-sm">{sourceValue(field, entry.value)}</p><p className="text-xs text-muted">{({ CUSTOMER_STATED: "Customer stated", OPERATOR_OBSERVED: "Operator observed", INFERRED: "Inferred - unverified" })[entry.provenance.assertion]}; observed {entry.provenance.observed_at || "time unknown"}.</p>{entry.provenance.source_type === "IMPORT_ROW" ? <Link className="text-xs text-brand underline" to={"/imports/" + encodeURIComponent(entry.provenance.import_id) + "?row=" + encodeURIComponent(entry.provenance.import_row_id)}>Open exact imported source row</Link> : <p className="text-xs text-muted">Manual source: {entry.provenance.source_reference}</p>}</div>)}</div>; }
