import { Link } from "react-router-dom";
import { currentnessLabels, intelligenceFieldLabel, type FactAssessment, type IntelligenceCurrentness, type IntelligenceFreshness } from "@/types/intelligence-currentness";
import { CurrentnessReasonText, InputRevisions } from "./recommendation-changes";
export function CurrentnessBadge({ currentness }: { currentness?: IntelligenceCurrentness }) { return <span className={"inline-block rounded px-2 py-1 text-xs font-medium " + (currentness?.state === "CURRENT" ? "bg-ok-light text-ok" : currentness?.state === "OUTDATED" ? "bg-warn-light text-warn" : "bg-soft text-muted")}>{currentness ? currentnessLabels[currentness.state] : "Currentness unavailable"}</span>; }
export function IntelligenceCurrentnessPanel({ leadId, currentness, freshness, checking, error, onCheck }: { leadId: string; currentness?: IntelligenceCurrentness; freshness?: IntelligenceFreshness; checking: boolean; error: boolean; onCheck: () => void }) {
  return <section aria-label="Analysis currentness and source review" className="rounded-xl border border-line bg-surface p-4 space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Analysis currentness</h3><CurrentnessBadge currentness={currentness} /></div>
    {error && <p role="alert" className="text-sm text-warn">Currentness could not be checked. Displayed information may be outdated. Check saved state before refreshing analysis or reviewing work.</p>}
    {currentness ? <><p className="text-sm text-muted">{currentness.state === "CURRENT" ? "This analysis reflects the saved inputs at the last check. Missing, conflicting or aged facts can still need review." : currentness.state === "OUTDATED" ? "Saved inputs or their freshness changed after the previous analysis. Review the reasons and refresh analysis when appropriate." : currentness.state === "ARCHIVED" ? "Archived records retain their history. Restore this record before refreshing analysis." : "No analysis is available for the current saved inputs. Review the source information before analysing."} Currentness does not establish business fit or permission to contact.</p>
      <dl className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs"><div><dt className="font-medium">Last analysed</dt><dd>{date(currentness.analysed_at, "No previous analysis")}</dd></div><div><dt className="font-medium">Last checked</dt><dd>{date(currentness.assessed_at, "Unknown")}</dd></div><div><dt className="font-medium">Next source transition</dt><dd>{date(currentness.next_check_at, "None currently scheduled")}</dd></div></dl>
      {currentness.reasons.length > 0 && <ul className="list-disc pl-5 text-sm">{currentness.reasons.map((reason, index) => <li key={index}><CurrentnessReasonText reason={reason} /> <ReviewLink leadId={leadId} scope={reason.scope} /></li>)}</ul>}
      <details><summary className="cursor-pointer text-sm text-brand">Compared input revisions</summary><div className="mt-2 space-y-2"><p className="text-xs font-medium">Analysed inputs</p><InputRevisions revisions={currentness.evaluated_revisions} /><p className="text-xs font-medium">Current saved inputs</p><InputRevisions revisions={currentness.current_revisions} /></div></details>
    </> : <p className="text-sm text-muted">Current analysis status is not available.</p>}
    <p className="rounded-lg bg-soft p-3 text-sm text-muted">Refresh analysis reassesses saved sources. It does not ask the customer to confirm them, change their observation dates or resolve conflicting accounts. Review any prepared outbound work separately.</p>
    <button type="button" onClick={onCheck} disabled={checking} className="text-sm text-brand underline disabled:opacity-50">{checking ? "Checking saved state..." : "Check saved state"}</button><p className="text-xs text-muted">While this view is open, currentness is checked periodically and when a recorded source reaches its next transition. These checks do not run analysis.</p>
    {freshness && <SourceReview leadId={leadId} freshness={freshness} />}
  </section>;
}
function date(value: string | null | undefined, missing: string) { if (!value) return missing; const time = Date.parse(value); return Number.isFinite(time) ? new Date(time).toLocaleString() : "Invalid recorded timestamp"; }
function ReviewLink({ leadId, scope }: { leadId: string; scope: string }) { const path = scope === "BUSINESS" ? "/settings" : scope === "LEAD" ? "/leads/" + leadId + "?tab=data" : "/leads/" + leadId + "?tab=enquiry"; return ["BUSINESS", "LEAD", "ENQUIRY"].includes(scope) ? <Link className="text-brand underline" to={path}>Review {scope === "BUSINESS" ? "business profile" : scope === "LEAD" ? "contact details" : "enquiry context"}</Link> : null; }
function SourceReview({ leadId, freshness }: { leadId: string; freshness: IntelligenceFreshness }) {
  const facts = Object.values(freshness.facts);
  return <section aria-label="Saved source quality" className="space-y-3 border-t border-line pt-4"><h4 className="font-semibold text-sm">Saved source quality</h4><p className="text-xs text-muted">Ongoing enquiry and research facts use a provisional 90-day observation policy. Historical enquiry dates and interactions keep their historical meaning. Missing observation time is not proof of freshness.</p>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">{facts.map(fact => <article key={fact.field} aria-label={intelligenceFieldLabel(fact.field) + " source assessment"} className="min-w-0 rounded-lg border border-line p-3 space-y-2"><h5 className="text-sm font-medium">{intelligenceFieldLabel(fact.field)}</h5><FactStatus fact={fact} /><Link className="inline-block text-xs text-brand underline" to={"/leads/" + leadId + "?tab=enquiry"}>Review saved fact and history</Link></article>)}</div>
    {freshness.research.length > 0 && <details><summary className="cursor-pointer text-sm text-brand">Research source assessments ({freshness.research.length})</summary><div className="mt-3 space-y-3">{freshness.research.map(fact => <article key={fact.id} className="rounded-lg border border-line p-3 space-y-2"><h5 className="text-sm font-medium">{intelligenceFieldLabel(fact.field)}</h5><FactStatus fact={fact} /><p className="text-xs text-muted break-all">Research record {fact.id}; ingestion {fact.ingestion_id}.</p></article>)}</div></details>}
    <p className="text-xs text-muted">Assessment checked {date(freshness.evaluated_at, "Unknown")}. Source values and corrections remain in their original histories.</p>
  </section>;
}
function FactStatus({ fact, conflictedAlternative = false }: { fact: FactAssessment; conflictedAlternative?: boolean }) {
  const labels = { CURRENT: "Within the observation window", STALE: "Observation is older than the policy window", AGE_UNKNOWN: "Observation time unknown", FUTURE_DATED: "Observation was later than its recording time", INVALID_TIME: "Observation time is invalid", HISTORICAL: "Historical fact", NOT_APPLICABLE: "No ongoing fact to age" };
  return <div className="space-y-1 text-xs"><p className={fact.usable ? "text-muted" : "text-warn"}>{fact.value_state === "UNKNOWN" ? "Unknown value" : fact.value_state === "CONFLICTED" ? "Conflicting values - review needed" : fact.assertion === "INFERRED" ? "Inferred - unverified" : fact.assertion === "CUSTOMER_STATED" ? "Customer stated" : fact.assertion === "OPERATOR_OBSERVED" ? "Operator observed" : "Recorded source"}. {labels[fact.freshness]}.</p><p className="text-muted">{conflictedAlternative ? "An alternative account; no value is selected from this conflict." : fact.usable ? "Usable within this assessment; source truth is not independently verified." : "Not usable as an established current assertion."}</p>{fact.freshness !== "AGE_UNKNOWN" && fact.reasons.includes("AGE_UNKNOWN") && <p className="text-muted">Observation time unknown; retained only as recorded history.</p>}{fact.reasons.includes("SOURCE_NOT_PERSISTED") && <p className="text-warn">This research source has not been accepted into the saved evidence.</p>}{fact.observed_at && <p className="text-muted">Observed: {date(fact.observed_at, "Unknown")}</p>}{fact.expires_at && <p className="text-muted">Observation window ends: {date(fact.expires_at, "Unknown")}</p>}{fact.source_reference && <details><summary className="cursor-pointer text-brand">Recorded source reference</summary><p className="break-all whitespace-pre-wrap mt-1 text-muted">{fact.source_reference}</p></details>}{fact.alternatives?.map((alternative, index) => <div className="border-l-2 border-line pl-2 mt-2" key={index}><p className="font-medium">Alternative {index + 1}</p><FactStatus fact={alternative} conflictedAlternative /></div>)}</div>;
}
