import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api, ApiError } from "@/lib/api";
import { useMe } from "@/hooks/use-auth";
import { useWorkspaceStore } from "@/stores/workspace";
import { feedbackError, feedbackUnavailable, useFeedbackHistory, useFeedbackTarget } from "@/hooks/use-intelligence-feedback";
import { feedbackKindLabels, replyCategoryLabels, type FeedbackCommand, type FeedbackLabels, type FeedbackReview, type FeedbackRevision, type FeedbackTargetRef } from "@/types/intelligence-feedback";
import { contextFieldClass } from "./context-editor";
const button = "rounded-lg border border-line px-3 py-2 text-sm text-brand disabled:opacity-50";
export function FeedbackLauncher({ target, label }: { target: FeedbackTargetRef | null; label?: string }) {
  const { data: me } = useMe(), org = useWorkspaceStore(s => s.currentOrg), [captured, setCaptured] = useState<FeedbackTargetRef | null>(null);
  const owner = me?.user.role === "OWNER" && me.user.organization_id === org?.id;
  return <>{owner && <button type="button" className={button} disabled={!target} onClick={() => setCaptured(target && { ...target })}>{label || "Review this assessment"}</button>}{captured && owner && <FeedbackDialog key={org?.id + ":" + captured.target_id} target={captured} close={() => setCaptured(null)} />}</>;
}
function FeedbackDialog({ target, close }: { target: FeedbackTargetRef; close: () => void }) {
  const query = useFeedbackTarget(target), closeButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; closeButton.current?.focus(); return () => previous?.focus(); }, []);
  return <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/50 p-3 sm:p-8"><section role="dialog" aria-modal="true" aria-label="Review saved assessment" className="w-full max-w-3xl space-y-4 rounded-2xl bg-surface p-4 shadow-xl sm:p-6" onKeyDown={event => { if (event.key !== "Tab") return; const nodes = [...event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),summary')]; const first = nodes[0], last = nodes.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }}>
    <div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Review saved assessment</h2><p className="text-sm text-muted">{feedbackKindLabels[target.target_kind]}</p></div><button ref={closeButton} type="button" className={button} onClick={close}>Close review</button></div>
    <p className="text-sm text-muted">Your judgment is an audited review of this exact result. It does not replace source facts, change the recorded interpretation, resolve a task or release contact restrictions.</p>
    {query.isError && <p role="alert" className="text-sm text-warn">The saved assessment could not be checked. Displayed data may be outdated; writing requires a successful check.</p>}
    {query.data ? <FeedbackEditor target={target} initial={query.data} uncertain={query.isError} refresh={async () => { const result = await query.refetch(); return result.error ? null : result.data || null; }} /> : <p role="status">{query.isError ? "Saved assessment unavailable." : "Loading exact saved assessment..."}</p>}
    <button type="button" className={button} disabled={query.isFetching} onClick={() => void query.refetch()}>Check saved assessment</button>
  </section></div>;
}
function storageKey(org: string, target: FeedbackTargetRef) { return "relay-feedback-request:" + org + ":" + target.target_kind + ":" + target.target_id; }
function FeedbackEditor({ target, initial, uncertain, refresh }: { target: FeedbackTargetRef; initial: FeedbackReview; uncertain: boolean; refresh: () => Promise<FeedbackReview | null> }) {
  const org = useWorkspaceStore(s => s.currentOrg)!, client = useQueryClient(), key = storageKey(org.id, target);
  const [pending, setPending] = useState<FeedbackCommand | null>(() => { try { const command = JSON.parse(sessionStorage.getItem(key) || "null"); return command && command.lead_id === target.lead_id && command.target_id === target.target_id && command.target_kind === target.target_kind && typeof command.request_key === "string" ? command : null; } catch { return null; } });
  const [draft, setDraft] = useState(() => ({ correctness: pending?.labels?.correctness || "", usefulness: pending?.labels?.usefulness || "", expected: pending?.labels?.expected_category || "", evalUse: pending?.labels?.eval_use || "OPERATIONAL_ONLY", reason: pending?.reason || "", revision: pending?.expected_feedback_revision ?? initial.feedback?.revision ?? 0, token: pending?.review_token || initial.review_token }));
  const [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [notice, setNotice] = useState<string | null>(null), [rejected, setRejected] = useState(false), [acceptedRevision, setAcceptedRevision] = useState<number | null>(null), confirmed = useRef<string | null>(null);
  const lookup = useQuery({ queryKey: ["feedback-request", org.id, pending?.request_key], queryFn: () => api.get<{ feedback: FeedbackRevision | null }>("/intelligence-feedback/requests/" + encodeURIComponent(pending!.request_key)), enabled: Boolean(pending), retry: false, refetchInterval: pending ? 5000 : false });
  function accept(saved: FeedbackRevision, requestKey: string) { if (confirmed.current === requestKey) return; confirmed.current = requestKey; setAcceptedRevision(saved.revision); sessionStorage.removeItem(key); setPending(null); setError(null); setRejected(false); setNotice("Request recorded as review revision " + saved.revision + ". Later review revisions, if any, remain in history."); setDraft(previous => ({ ...previous, revision: saved.revision })); for (const prefix of ["feedback-target", "feedback-history", "feedback-candidates", "evaluation-datasets", "evaluation-dataset", "evaluation-results"]) void client.invalidateQueries({ queryKey: [prefix] }); }
  useEffect(() => { if (pending && lookup.data?.feedback) accept(lookup.data.feedback, pending.request_key); }, [lookup.data, pending?.request_key]);
  async function send(command: FeedbackCommand) { setBusy(true); setError(null); try { const response = await api.post<{ feedback: FeedbackRevision; replayed: boolean }>("/intelligence-feedback", command); accept(response.feedback, command.request_key); } catch (failure) { if (confirmed.current !== command.request_key) { setError(feedbackError(failure)); const code = failure instanceof ApiError && failure.body && typeof failure.body === "object" ? (failure.body as { code?: string }).code : null; setRejected(Boolean(code && ["FEEDBACK_REVISION_STALE", "FEEDBACK_REVIEW_STALE", "FEEDBACK_INVALID_INPUT", "FEEDBACK_EVALUATION_INPUT_REQUIRED"].includes(code))); void refresh(); void lookup.refetch(); } } finally { setBusy(false); } }
  useEffect(() => { if (!pending && acceptedRevision !== null && initial.feedback?.revision === acceptedRevision && draft.revision === acceptedRevision && initial.can_record && initial.review_token && draft.token !== initial.review_token) setDraft(previous => ({ ...previous, token: initial.review_token })); }, [initial.review_token, initial.feedback?.revision, acceptedRevision, pending, draft.revision, draft.token, initial.can_record]);
  const stale = draft.revision !== (initial.feedback?.revision || 0) || draft.token !== initial.review_token;
  const nominated = draft.evalUse !== "OPERATIONAL_ONLY", valid = Boolean(draft.correctness && draft.usefulness && draft.reason.trim() && (!nominated || target.target_kind === "REPLY" && initial.target.evaluation_input_available && draft.correctness !== "UNCLEAR" && draft.expected));
  async function submit(operation: "RECORD" | "WITHDRAW") { if (busy || pending || stale || uncertain || !initial.can_record || !draft.token || !draft.reason.trim() || operation === "RECORD" && !valid) return; const command: FeedbackCommand = { ...target, expected_feedback_revision: draft.revision, review_token: draft.token, request_key: crypto.randomUUID(), operation, reason: draft.reason, labels: operation === "WITHDRAW" ? null : { correctness: draft.correctness as FeedbackLabels["correctness"], usefulness: draft.usefulness as FeedbackLabels["usefulness"], expected_category: target.target_kind === "REPLY" && draft.expected ? draft.expected as FeedbackLabels["expected_category"] : null, eval_use: target.target_kind === "REPLY" ? draft.evalUse as FeedbackLabels["eval_use"] : "OPERATIONAL_ONLY" } }; try { sessionStorage.setItem(key, JSON.stringify(command)); } catch { setError("The recovery reference could not be saved in this browser. Allow session storage before recording feedback."); return; } setPending(command); setNotice(null); setRejected(false); await send(command); }
  async function rebase() { const latest = await refresh(); if (!latest) { setError("Latest review could not be checked. Your draft is retained."); return; } if (pending && !rejected) { setError("Check the unconfirmed request before replacing its revision."); return; } sessionStorage.removeItem(key); setPending(null); setRejected(false); setDraft(previous => ({ ...previous, revision: latest.feedback?.revision || 0, token: latest.review_token })); setError(null); setNotice("Latest saved revision checked. Your judgments and reason remain for a new explicit decision."); }
  return <><article className="space-y-2 rounded-xl border border-line bg-soft p-3"><h3 className="font-semibold">{initial.target.presentation.title}</h3><p className="whitespace-pre-wrap break-words text-sm">{initial.target.presentation.summary}</p>{initial.target.presentation.fields.map((field, index) => <p key={index} className="whitespace-pre-wrap break-words text-sm"><span className="font-medium">{field.label}: </span>{field.value}</p>)}{initial.target.presentation.truncated && <p className="text-xs text-warn">This is a bounded display. The saved source digest identifies the complete captured target.</p>}<details><summary className="cursor-pointer text-xs text-brand">Exact reviewed result</summary><p className="mt-2 break-all text-xs">{target.target_kind}: {target.target_id}</p><p className="text-xs">Recorded version {initial.target.version ?? "not recorded"}; pipeline {initial.target.pipeline_version || "not recorded"}. Captured status: {initial.target.status}.</p><p className="break-all text-xs">Source digest: {initial.target.source_sha256 || "Unavailable"}</p></details></article>
    {!initial.can_record && <p role="alert" className="text-sm text-warn">{feedbackUnavailable(initial.unavailable_reason)}</p>}
    <form aria-label="Assessment feedback editor" onSubmit={event => { event.preventDefault(); void submit("RECORD"); }} className="space-y-3">
      <p className="text-xs text-muted">Saved review revision {initial.feedback?.revision || 0}; editing revision {draft.revision}. {initial.feedback?.status === "WITHDRAWN" ? "The latest review is withdrawn. A new explicit review retains that history." : ""}</p>
      <fieldset disabled={busy || Boolean(pending)} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Your correctness judgment<select aria-label="Your correctness judgment" className={contextFieldClass} value={draft.correctness} onChange={event => setDraft({ ...draft, correctness: event.target.value })}><option value="">Choose a judgment</option><option value="CORRECT">Correct against the reviewed evidence</option><option value="INCORRECT">Incorrect against the reviewed evidence</option><option value="UNCLEAR">Cannot determine correctness</option></select></label><label className="text-sm">Usefulness to your work<select aria-label="Usefulness to your work" className={contextFieldClass} value={draft.usefulness} onChange={event => setDraft({ ...draft, usefulness: event.target.value })}><option value="">Choose a judgment</option><option value="USEFUL">Useful</option><option value="NOT_USEFUL">Not useful</option><option value="NOT_ASSESSED">Usefulness not assessed</option></select></label></div>
      {target.target_kind === "REPLY" && <><label className="block text-sm">Your expected reply category<select aria-label="Your expected reply category" className={contextFieldClass} value={draft.expected} onChange={event => setDraft({ ...draft, expected: event.target.value })}><option value="">Not labeled for replay</option>{Object.entries(replyCategoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm">Evaluation use<select aria-label="Evaluation use" className={contextFieldClass} value={draft.evalUse} onChange={event => setDraft({ ...draft, evalUse: event.target.value as FeedbackLabels["eval_use"] })}><option value="OPERATIONAL_ONLY">Operational review only — excluded from evaluation</option><option value="SYNTHETIC">Nominate synthetic example</option><option value="PERMISSION_REVIEWED">Nominate after reviewing processing permission</option></select></label><p className="text-xs text-muted">Nomination is your attestation, not confirmed permission or dataset inclusion. Describe its basis in the reason. No model training, provider submission or automatic dataset creation occurs.</p>{!initial.target.evaluation_input_available && <p className="text-xs text-warn">Usable original reply text is unavailable; evaluation nomination is not available.</p>}</>}
      <label className="block text-sm">Reason and evidence for your review<textarea required maxLength={2000} rows={3} className={contextFieldClass} value={draft.reason} onChange={event => setDraft({ ...draft, reason: event.target.value })} /></label></fieldset>
      {(error || stale) && <p role="alert" className="text-sm text-warn">{error || "A newer saved review is available. Your draft still belongs to its original reviewed revision."}</p>}{notice && <p role="status" className="text-sm text-ok">{notice}</p>}
      <div className="flex flex-wrap gap-2"><button type="submit" className={button} disabled={busy || Boolean(pending) || stale || uncertain || !valid || !initial.can_record}>Record review</button><button type="button" className={button} disabled={busy || Boolean(pending) || stale || uncertain || !draft.reason.trim() || initial.feedback?.status !== "RECORDED" || !initial.can_record} onClick={() => void submit("WITHDRAW")}>Withdraw current review</button>{(stale || error) && <button type="button" className={button} disabled={busy || Boolean(pending && !rejected)} onClick={() => void rebase()}>Review latest saved feedback</button>}</div>
    </form>
    {pending && <section aria-label="Feedback request recovery" className="space-y-2 rounded-lg border border-warn/30 bg-warn-light p-3 text-sm"><p>{busy ? "Recording review..." : "This exact request has not been confirmed. Checking its saved state does not write feedback."}</p><p className="break-all text-xs">Request reference: {pending.request_key}</p>{lookup.isError && <p role="alert">Saved request lookup failed. Keep the reference and check again.</p>}<div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={busy || lookup.isFetching} onClick={() => void lookup.refetch()}>Check feedback request</button><button type="button" className={button} disabled={busy || rejected} onClick={() => void send(pending)}>Retry same feedback request</button></div></section>}
    <Link className="inline-block text-sm text-brand underline" to={"/leads/" + target.lead_id + "?tab=enquiry"}>Review or correct the saved source separately</Link><FeedbackHistoryView target={target} initial={initial} />
  </>;
}
function FeedbackHistoryView({ target, initial }: { target: FeedbackTargetRef; initial: FeedbackReview }) {
  const [before, setBefore] = useState<number | null>(null), query = useFeedbackHistory(target, before, before !== null), history = before === null ? initial.history : query.data;
  return <section aria-label="Assessment review history" className="space-y-3 border-t border-line pt-4"><h3 className="font-semibold">Review history</h3><p className="text-xs text-muted">These are recorded owner judgments, not independently verified labels. Earlier revisions remain unchanged.</p>{query.isError && <p role="alert">Earlier review history could not be loaded.</p>}{history?.changes.length === 0 && <p className="text-sm text-muted">No saved review yet.</p>}{history?.changes.map(item => <article key={item.revision} className="space-y-2 rounded-lg border border-line p-3 text-sm"><p className="font-medium">Revision {item.revision} · {item.status === "WITHDRAWN" ? "Withdrawn" : "Recorded"}</p><p className="whitespace-pre-wrap break-words">{item.reason}</p>{item.labels && <p className="text-xs text-muted">{item.labels.correctness === "CORRECT" ? "Reviewed as correct" : item.labels.correctness === "INCORRECT" ? "Reviewed as incorrect" : "Correctness unclear"}; {item.labels.usefulness === "USEFUL" ? "useful" : item.labels.usefulness === "NOT_USEFUL" ? "not useful" : "usefulness not assessed"}. {item.labels.expected_category && "Expected: " + replyCategoryLabels[item.labels.expected_category] + ". "}{item.labels.eval_use === "OPERATIONAL_ONLY" ? "Excluded from evaluation." : "Nominated for review; dataset inclusion is separate."}</p>}<p className="break-all text-xs text-muted">{new Date(item.created_at).toLocaleString()} · Owner {item.created_by}</p></article>)}<div className="flex gap-2"><button type="button" className={button} disabled={before === null || query.isFetching} onClick={() => setBefore(null)}>Latest reviews</button><button type="button" className={button} disabled={!history?.has_more || history.next_before_revision === null || query.isFetching} onClick={() => setBefore(history!.next_before_revision)}>Older reviews</button></div></section>;
}
