import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { useMe } from "@/hooks/use-auth";
import { useLeadData, useLeadDataOperations, leadDataError } from "@/hooks/use-lead-data";
import { ApiError } from "@/lib/api";
import { contextFieldClass } from "./context-editor";
import { leadValueLabels, type ArchiveCommand, type LeadDataChange, type LeadDataCommand, type LeadDataCurrent, type LeadDataPreview, type LeadDataResult, type LeadPolicySummary, type LeadValues, type PhoneRegion } from "@/types/lead-data";
const button = "rounded-lg border border-line px-3 py-2 text-sm text-brand disabled:opacity-50";
const fields = Object.keys(leadValueLabels) as (keyof LeadValues)[];
type PendingCommand = { kind: "save"; command: LeadDataCommand } | { kind: "archive"; command: ArchiveCommand };
function unavailable(reason: string | null) {
  const messages: Record<string, string> = { LEAD_DATA_POLICY_PENDING: "Contact policy is still processing a mandatory receipt. Wait for it to finish before correcting contact details.", LEAD_ARCHIVED: "Restore this archived lead before correcting its contact details.", LEAD_DATA_NO_CHANGE: "No contact details changed.", LEAD_DATA_CANDIDATE_LIMIT: "Too many matching records to review safely here. Operational review is required.", LEAD_DATA_POLICY_LIMIT: "Too many contact restrictions to review safely here. Operational review is required.", LEAD_DATA_WORK_LIMIT: "Too much existing work to review safely here. Operational review is required." };
  return reason && messages[reason] || "This change is unavailable. Refresh saved data and review again.";
}
export function LeadDataManagement({ leadId }: { leadId: string }) {
  const query = useLeadData(leadId);
  if (!query.data) return <section className="p-5 text-sm" role={query.isError ? "alert" : "status"}>{query.isError ? "Lead data could not load." : "Loading saved lead data..."}{query.isError && <button className={button} onClick={() => void query.refetch()}>Try again</button>}</section>;
  return <LeadDataEditor key={leadId} leadId={leadId} current={query.data.current} refreshError={query.isError} />;
}
function LeadDataEditor({ leadId, current, refreshError }: { leadId: string; current: LeadDataCurrent; refreshError: boolean }) {
  const { data: me } = useMe(), operations = useLeadDataOperations(leadId);
  const owner = me?.user.role === "OWNER";
  const [draft, setDraft] = useState<LeadValues>(() => structuredClone(current.values)), [revision, setRevision] = useState(current.data_revision);
  const [region, setRegion] = useState<PhoneRegion>("INTERNATIONAL_ONLY"), [reason, setReason] = useState("");
  const [preview, setPreview] = useState<LeadDataPreview | null>(null), [confirmed, setConfirmed] = useState(false), [conflict, setConflict] = useState(false);
  const [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [message, setMessage] = useState<string | null>(null);
  const [archiveDraft, setArchiveDraft] = useState<{ archived: boolean; reason: string } | null>(null);
  const [archiveOpen, setArchiveOpen] = useState(false), [replacePrompt, setReplacePrompt] = useState(false);
  const [uncertain, setUncertain] = useState<PendingCommand | null>(null), [retryReady, setRetryReady] = useState(false);
  const stale = conflict || revision !== current.data_revision;
  function load(next: LeadDataCurrent) { setDraft(structuredClone(next.values)); setRevision(next.data_revision); setPreview(null); setReason(""); setConfirmed(false); setConflict(false); setReplacePrompt(false); setRegion("INTERNATIONAL_ONLY"); }
  function change(next: LeadValues) { setDraft(next); setPreview(null); setConfirmed(false); setMessage(null); }
  async function reload() { setBusy(true); setError(null); try { load((await operations.latest()).current); } catch (failure) { setError(leadDataError(failure)); } finally { setBusy(false); } }
  async function review() { setBusy(true); setError(null); setMessage(null); setConfirmed(false); try { setPreview(await operations.preview({ expected_revision: revision, values: draft, default_phone_region: region })); } catch (failure) { setError(leadDataError(failure)); if (failure instanceof ApiError && failure.status === 409) setConflict(true); } finally { setBusy(false); } }
  async function checkSaved(pending: PendingCommand) {
    setRetryReady(false);
    try {
      const latest = await operations.latest();
      if (latest.current.data_revision > pending.command.expected_revision) {
        setUncertain(null); setConflict(true); setArchiveOpen(false); setError(null); setMessage("A saved change exists after this request's revision. Inspect the current data and change history below before starting another change. Your draft is preserved.");
      } else { setRetryReady(true); setError("No newer saved revision was found. You may retry the exact same request; it may still be completing."); }
    } catch { setError("The request and current history could not be confirmed. Check saved data before retrying. Closing this page does not undo an accepted request."); }
  }
  async function send(pending: PendingCommand) {
    if (busy) return;
    setBusy(true); setError(null); setMessage(null);
    try {
      const result: LeadDataResult = pending.kind === "save" ? await operations.save(pending.command) : await operations.archive(pending.command);
      load(result.current); setUncertain(null); setArchiveOpen(false); setArchiveDraft(null);
      if (result.replayed) { try { load((await operations.latest()).current); } catch { setError("The original saved request was confirmed, but latest data could not refresh. Load saved data before making another change."); setConflict(true); } }
      setMessage((result.replayed ? "Previously saved request confirmed. " : result.changed ? "Change saved. " : "No change was needed. ") + "Revision " + result.current.data_revision + ". Blocked actions: " + result.effects.blocked_actions + "; cancelled follow-ups: " + result.effects.cancelled_follow_ups + "; stopped workflows: " + result.effects.stopped_workflows + ".");
    } catch (failure) {
      setConfirmed(false);
      if (failure instanceof ApiError && failure.status >= 400 && failure.status < 500) { setUncertain(null); setRetryReady(false); setError(leadDataError(failure)); if (failure.status === 409) { setConflict(true); setArchiveOpen(false); } }
      else { setUncertain(pending); setArchiveOpen(false); await checkSaved(pending); }
    } finally { setBusy(false); }
  }
  return <section className="max-w-5xl min-w-0 space-y-6" aria-label="Lead data management">
    <div><h2 className="text-lg font-semibold">Contact details and record history</h2><p className="mt-1 text-sm text-muted">Correct one enquiry's contact details with an explicit reason. Original imports and enquiry fact sources remain in their own history.</p></div>
    <section className="rounded-xl border border-line p-4 space-y-3" aria-label="Current saved lead data"><h3 className="font-semibold">Current saved data - revision {current.data_revision}</h3><p className="text-sm">{current.archived_at ? "Archived on " + new Date(current.archived_at).toLocaleString() : "Current record"}</p><SavedValues current={current} /></section>
    {refreshError && <p role="alert" className="text-sm text-warn">Saved data could not refresh. Displayed values may be outdated; your draft is preserved.</p>}
    {error && <p role="alert" className="rounded-lg border border-warn p-3 text-sm text-warn">{error}</p>}
    {message && <p role="status" className="rounded-lg bg-soft p-3 text-sm">{message}</p>}
    {uncertain && <section aria-label="Unconfirmed data change" className="rounded-xl border border-warn p-4 space-y-3"><h3 className="font-semibold">Check saved data before retrying</h3><p className="text-sm">The original request is retained. No new change can be submitted until its saved state is checked.</p><button className={button} disabled={busy} onClick={async () => { setBusy(true); await checkSaved(uncertain); setBusy(false); }}>Check saved data</button>{retryReady && <button className={button + " ml-3"} disabled={busy} onClick={() => void send(uncertain)}>Retry same request</button>}</section>}
    {owner && !current.archived_at && <form className="rounded-xl border border-line p-4 space-y-4" aria-label="Correct contact details" onSubmit={event => { event.preventDefault(); if (!busy && !stale && !uncertain) void review(); }}><h3 className="font-semibold">Correct contact details</h3>
      {stale && <p role="alert" className="text-sm text-warn">This record or its review changed. Your draft is preserved. Load the latest saved data before reviewing another correction.</p>}
      <fieldset disabled={busy || !!uncertain} className="grid grid-cols-1 sm:grid-cols-2 gap-3">{fields.map(field => <label key={field} className="block text-sm space-y-1">{leadValueLabels[field]}<input aria-label={"Corrected " + leadValueLabels[field].toLowerCase()} className={contextFieldClass} required={field === "name"} maxLength={{name:200,email:320,phone:80,company:200}[field]} value={draft[field] || ""} onChange={event => change({ ...draft, [field]: field === "name" ? event.target.value : event.target.value || null })} /></label>)}
        <label className="block text-sm space-y-1">Phone interpretation<select aria-label="Correction phone interpretation" className={contextFieldClass} value={region} onChange={event => { setRegion(event.target.value as PhoneRegion); setPreview(null); setConfirmed(false); }}><option value="INTERNATIONAL_ONLY">International number with explicit + country code</option><option value="IN">India (+91) for a national number</option><option value="US">United States (+1) for a national number</option></select></label>
      </fieldset><p className="text-xs text-muted">Blank optional fields become unknown. Letters are not stripped from phone numbers. Choose the country for a national number; inspect the normalized contact below.</p>
      <button type="submit" className={button} disabled={busy || stale || !!uncertain}>Preview contact correction</button>
      {preview && <section aria-label="Contact correction preview" className="space-y-4 border-t border-line pt-4"><h4 className="font-semibold">Review before saving</h4><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th className="p-2">Field</th><th className="p-2">Saved</th><th className="p-2">Proposed normalized value</th></tr></thead><tbody>{fields.map(field => <tr key={field} className="border-t border-line"><th className="p-2 text-left font-medium">{leadValueLabels[field]}{preview.changed_fields.includes(field) ? " (changed)" : ""}</th><td className="p-2 break-all">{preview.current.values[field] || "Unknown"}</td><td className="p-2 break-all">{preview.proposed.normalized_values[field === "email" ? "normalized_email" : field === "phone" ? "normalized_phone" : field] || "Unknown"}</td></tr>)}</tbody></table></div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><Policy title="Current contact policy" policy={preview.current_policy} /><Policy title="Proposed contact policy" policy={preview.proposed_policy} /></div>
        <p className="rounded-lg bg-soft p-3 text-sm">This correction carries {preview.effects.carried_restrictions} existing restriction(s), blocks {preview.effects.blocked_actions} queued action(s), cancels {preview.effects.cancelled_follow_ups} automatic follow-up(s), and stops {preview.effects.stopped_workflows} workflow(s). Existing human follow-ups stay available. Refresh intelligence and review new actions after saving. No sending permission is granted.</p>
        <div className="space-y-2"><p className="text-sm font-medium">Matching enquiries: showing {preview.duplicate_candidates.length} of {preview.duplicate_total}</p>{preview.duplicates_truncated && <p className="text-xs text-warn">The displayed candidate list is incomplete. Other matching enquiries exist.</p>}{preview.duplicate_candidates.map(candidate => <p key={candidate.lead.id} className="text-sm"><Link className="text-brand underline" target="_blank" rel="noreferrer" to={"/leads/" + encodeURIComponent(candidate.lead.id) + "?tab=data"}>{candidate.lead.name || candidate.lead.id}</Link>{candidate.lead.archived_at ? " (archived)" : ""} - {candidate.match_types.map(type => ({ STRONG_EMAIL: "matching email", STRONG_PHONE: "matching phone", POSSIBLE_NAME_COMPANY: "possible name and company match" }[type] || type.replaceAll("_", " ").toLowerCase())).join(", ")}; {candidate.lead.normalized_email || "unknown email"} / {candidate.lead.normalized_phone || "unknown phone"}</p>)}<p className="text-xs text-muted">A correction does not merge these enquiries or treat their contact addresses as verified aliases.</p></div>
        {!preview.can_save && <p role="alert" className="text-sm text-warn">{unavailable(preview.unavailable_reason)}</p>}
        <label className="block text-sm space-y-1">Correction reason<textarea aria-label="Correction reason" className={contextFieldClass} rows={2} maxLength={2000} value={reason} disabled={busy || !!uncertain} onChange={event => { setReason(event.target.value); setConfirmed(false); }} /></label>
        <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={confirmed} disabled={busy || !!uncertain} onChange={event => setConfirmed(event.target.checked)} />I reviewed the normalized contact, matching enquiries and affected work.</label>
        <button type="button" className="rounded-lg bg-brand px-4 py-2 text-sm text-white disabled:opacity-50" disabled={busy || stale || !!uncertain || !preview.can_save || !preview.review_token || !reason.trim() || !confirmed} onClick={() => { if (preview.review_token) void send({ kind: "save", command: { expected_revision: revision, values: structuredClone(draft), default_phone_region: region, review_token: preview.review_token, reason: reason.trim() } }); }}>Save contact correction</button>
      </section>}
    </form>}
    {!owner && <p className="text-sm text-muted">A workspace owner can correct, archive or restore this record.</p>}
    {current.archived_at && <p className="rounded-lg bg-soft p-3 text-sm">Archived records remain readable and exportable. Restore this record before editing contact details or enquiry context, analysing, or creating outbound work. Restoration does not restart any work or remove restrictions.</p>}
    {!uncertain && <div className="flex flex-wrap items-center gap-3"><button className={button} disabled={busy} onClick={() => setReplacePrompt(true)}>Load latest saved data</button>{replacePrompt && <><span className="text-xs text-warn">Replace this correction draft with the latest saved values?</span><button className={button} disabled={busy} onClick={() => void reload()}>Replace draft with latest</button><button className={button} onClick={() => setReplacePrompt(false)}>Keep draft</button></>}{owner && <button className={button} disabled={busy || stale} onClick={() => setArchiveOpen(true)}>{current.archived_at ? "Restore this lead" : "Archive this lead"}</button>}</div>}
    <DataHistory leadId={leadId} />
    {archiveOpen && <ArchiveDialog current={current} initialReason={archiveDraft?.archived === !current.archived_at ? archiveDraft.reason : ""} onReasonChange={(archived, reason) => setArchiveDraft({ archived, reason })} busy={busy} onClose={() => setArchiveOpen(false)} onConfirm={command => void send({ kind: "archive", command })} />}
  </section>;
}
function policyReason(reason: string) { return ({ OPT_OUT: "Opt-out", SUPPRESSED: "Suppressed by operator", UNSUBSCRIBE: "Unsubscribed", COMPLAINT: "Complaint", HARD_BOUNCE: "Hard bounce", DELIVERY_REVIEW: "Delivery review required" } as Record<string, string>)[reason] || reason.replaceAll("_", " ").toLowerCase(); }
function policyChannel(channel: string) { return ({ ALL: "All channels", EMAIL: "Email", WHATSAPP: "WhatsApp", SMS: "SMS", VOICE: "Voice" } as Record<string, string>)[channel] || channel.replaceAll("_", " ").toLowerCase(); }
function Policy({ title, policy }: { title: string; policy: LeadPolicySummary }) { return <div className="rounded-lg border border-line p-3 text-sm"><p className="font-medium">{title}</p><p>{policy.restricted ? "Restricted" : policy.policy_pending ? "Policy processing pending" : "No recorded restriction"} - {policy.restriction_count === null ? "Restriction count unavailable" : policy.restriction_count + " recorded restriction(s)"}.</p><ul className="mt-2 space-y-1">{policy.reasons.map(item => <li key={item.reason + ":" + item.channel}>{policyChannel(item.channel)}: {policyReason(item.reason)}</li>)}</ul>{policy.policy_incomplete && <p className="text-xs text-warn">This restriction comparison is incomplete and cannot authorize a correction.</p>}{policy.policy_pending && <p className="text-xs text-warn">Contact policy is still processing a mandatory receipt.</p>}{policy.restrictions_truncated && <p className="text-xs text-warn">Only a limited set of restriction references is displayed.</p>}</div>; }
function SavedValues({ current }: { current: LeadDataCurrent }) { return <dl className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">{fields.map(field => <div key={field} className="min-w-0"><dt className="font-medium">{leadValueLabels[field]}</dt><dd className="break-words">{current.values[field] || "Unknown"}<p className="text-xs text-muted">{current.field_provenance[field] ? "Corrected at revision " + current.field_provenance[field]!.revision + " by " + current.field_provenance[field]!.created_by : "Original recorded contact"}</p>{(field === "phone" || field === "email") && <p className="text-xs text-muted break-all">Normalized: {current.normalized_values[field === "phone" ? "normalized_phone" : "normalized_email"] || "Unknown"}</p>}</dd></div>)}</dl>; }
function DataHistory({ leadId }: { leadId: string }) {
  const [pages, setPages] = useState<(number | undefined)[]>([undefined]), [page, setPage] = useState(0), query = useLeadData(leadId, pages[page]);
  return <section aria-label="Lead data history" className="space-y-3 border-t border-line pt-5"><h3 className="font-semibold">Lead data history</h3>{query.isError ? <p role="alert" className="text-sm text-warn">History could not load. <button className={button} onClick={() => void query.refetch()}>Retry history</button></p> : query.data ? <>{!query.data.history.changes.length && <p className="text-sm text-muted">No contact correction or archive change recorded.</p>}{query.data.history.changes.map(change => <HistoryChange key={change.id} change={change} />)}<div className="flex gap-3 text-sm"><button className={button} disabled={page === 0} onClick={() => setPage(page - 1)}>Newer changes</button><span className="self-center">History page {page + 1}</span><button className={button} disabled={!query.data.history.has_more || !query.data.history.next_before_revision} onClick={() => { setPages([...pages.slice(0, page + 1), query.data!.history.next_before_revision!]); setPage(page + 1); }}>Older changes</button></div></> : <p role="status" className="text-sm">Loading history...</p>}</section>;
}
function HistoryChange({ change }: { change: LeadDataChange }) { return <details className="rounded-xl border border-line p-3 text-sm"><summary className="cursor-pointer font-medium">Revision {change.revision} - {change.kind === "CORRECT" ? "Contact corrected" : change.kind === "ARCHIVE" ? "Archived" : "Restored"} - {new Date(change.created_at).toLocaleString()}</summary><div className="mt-3 space-y-3"><p className="break-words">{change.reason}</p><p className="text-xs text-muted">Recorded by {change.created_by}. Change {change.id}.</p><div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><div className="rounded-lg bg-soft p-3 space-y-2"><h4 className="font-medium">Before - revision {change.before.data_revision}{change.before.archived_at ? " (archived)" : ""}</h4><SavedValues current={change.before} /></div><div className="rounded-lg bg-soft p-3 space-y-2"><h4 className="font-medium">After - revision {change.after.data_revision}{change.after.archived_at ? " (archived)" : ""}</h4><SavedValues current={change.after} /></div></div><p className="text-xs text-muted">Blocked actions: {change.effects.blocked_actions}; cancelled follow-ups: {change.effects.cancelled_follow_ups}; stopped workflows: {change.effects.stopped_workflows}. Restoring a record starts no new work.</p></div></details>; }
function ArchiveDialog({ current, initialReason, onReasonChange, busy, onClose, onConfirm }: { current: LeadDataCurrent; initialReason: string; onReasonChange: (archived: boolean, reason: string) => void; busy: boolean; onClose: () => void; onConfirm: (command: ArchiveCommand) => void }) {
  const dialog = useRef<HTMLDialogElement>(null), [reason, setReason] = useState(initialReason), [snapshot] = useState(() => structuredClone(current));
  const stale = snapshot.data_revision !== current.data_revision;
  useEffect(() => { const element = dialog.current; element?.showModal(); return () => element?.close(); }, []);
  const archived = !snapshot.archived_at;
  return <dialog ref={dialog} aria-labelledby="archive-title" onCancel={event => { if (busy) event.preventDefault(); else onClose(); }} className="fixed inset-0 m-auto w-[calc(100%_-_2rem)] max-w-xl rounded-xl border border-line bg-surface p-5 text-ink shadow-xl backdrop:bg-black/40"><form className="space-y-4" onSubmit={event => { event.preventDefault(); if (!busy && !stale && reason.trim()) onConfirm({ expected_revision: snapshot.data_revision, archived, reason: reason.trim() }); }}><h2 id="archive-title" className="text-lg font-semibold">{archived ? "Archive" : "Restore"} {snapshot.values.name}?</h2>{stale && <p role="alert" className="text-sm text-warn">This record changed while the dialog was open. Close it, load the latest data and review this decision again. Your reason is preserved.</p>}<p className="text-sm">{archived ? "Archive this one enquiry. Queued actions will be blocked, open workflows stopped, and all open follow-ups cancelled, including human tasks. Its source, intelligence, contact restrictions and change history remain available. Already dispatched or uncertain work may still require delivery review." : "Restore this one enquiry to the current directory. Contact restrictions and recorded status remain unchanged. No cancelled follow-up, stopped workflow, old analysis approval or queued action restarts."}</p><label className="block text-sm space-y-1">{archived ? "Archive" : "Restore"} reason<textarea aria-label="Archive or restore reason" required maxLength={2000} rows={3} className={contextFieldClass} disabled={busy} value={reason} onChange={event => { setReason(event.target.value); onReasonChange(archived, event.target.value); }} /></label><div className="flex gap-3"><button type="submit" disabled={busy || stale || !reason.trim()} className="rounded-lg bg-brand px-4 py-2 text-sm text-white disabled:opacity-50">{archived ? "Confirm archive" : "Confirm restore"}</button><button type="button" className={button} disabled={busy} onClick={onClose}>Cancel</button></div></form></dialog>;
}
