import {LoadingState} from "@/components/loading-screen";
import { useState } from "react";
import { Link } from "react-router-dom";
import { useLeadDirectory } from "@/hooks/use-lead-directory";
import { useMe } from "@/hooks/use-auth";
import { leadDataError } from "@/hooks/use-lead-data";
import { downloadLeadExport } from "@/lib/api";
import { contextFieldClass } from "./context-editor";
import { leadSourceLabels, type ArchiveFilter } from "@/types/lead-data";

export function LeadDirectory() {
  const directory = useLeadDirectory(), { query, view } = directory;
  const { data: me } = useMe();
  const owner = me?.user.role === "OWNER";
  const [exporting, setExporting] = useState(false), [feedback, setFeedback] = useState<string | null>(null), [error, setError] = useState<string | null>(null);
  const rows = query.data?.leads || [], ids = rows.map(row => row.id), selected = new Set(view.selected);
  const hidden = view.selected.filter(id => !ids.includes(id)).length;
  const allPage = rows.length > 0 && ids.every(id => selected.has(id));
  const wouldExceed = new Set([...view.selected, ...ids]).size > 1000;
  async function exportSelected() {
    if (!owner || exporting || !view.selected.length) return;
    const exactIds = [...view.selected]; setExporting(true); setFeedback(null); setError(null);
    try { const count = await downloadLeadExport(exactIds); setFeedback("Downloaded " + count + " selected records. Your selection is retained."); }
    catch (failure) { setError(leadDataError(failure)); }
    finally { setExporting(false); }
  }
  return <section className="flex-1 min-w-0 overflow-y-auto p-4 sm:p-6 space-y-4" aria-label="Lead directory">
    <div className="flex flex-wrap gap-2" role="group" aria-label="Archive filter">{([["ACTIVE", "Current"], ["ARCHIVED", "Archived"], ["ALL", "All records"]] as [ArchiveFilter, string][]).map(([value, label]) => <button type="button" key={value} aria-pressed={view.archive === value} onClick={() => directory.filters({ archive: value })} className={"rounded-lg px-3 py-2 text-sm border " + (view.archive === value ? "bg-brand text-white border-brand" : "border-line bg-surface text-ink")}>{label}</button>)}</div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><label className="text-sm space-y-1">Search leads<input aria-label="Search leads" maxLength={200} className={contextFieldClass} value={view.search} onChange={event => directory.filters({ search: event.target.value })} placeholder="Name, company, email or phone" /></label><label className="text-sm space-y-1">Source<select aria-label="Filter source" className={contextFieldClass} value={view.source} onChange={event => directory.filters({ source: event.target.value })}><option value="">All sources</option>{Object.entries(leadSourceLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm space-y-1">Recorded status<select aria-label="Filter recorded status" className={contextFieldClass} value={view.status} onChange={event => directory.filters({ status: event.target.value })}><option value="">All statuses</option>{["NEW", "NORMALIZED", "ACTIVE", "CONTACTED", "CONVERTED", "OPTED_OUT", "SUPPRESSED", "FAILED"].map(status => <option key={status}>{status}</option>)}</select></label></div>
    <div className="rounded-xl border border-line bg-surface p-4 space-y-3" aria-label="Selected record export"><div className="flex flex-wrap items-center gap-4"><p className="text-sm">{view.selected.length} selected for export; {hidden} not on this page.</p><button type="button" disabled={!owner || exporting || !rows.length || !allPage && wouldExceed} onClick={() => directory.select(ids, !allPage)} className="text-sm text-brand underline disabled:opacity-40">{allPage ? "Deselect this page" : "Select this page"}</button><button type="button" disabled={exporting || !view.selected.length} onClick={directory.clear} className="text-sm text-brand underline disabled:opacity-40">Clear export selection</button><button type="button" disabled={!owner || exporting || !view.selected.length} onClick={() => void exportSelected()} className="rounded-lg bg-brand px-4 py-2 text-sm text-white disabled:opacity-40">{exporting ? "Preparing selected export..." : "Export selected CSV (" + view.selected.length + ")"}</button></div><p className="text-xs text-muted">Choose up to 1000 records across pages or filters. Export includes exactly those IDs with their current saved values, including selected archived records. It never archives records. Spreadsheet display cells may use a visible text: label for safety and precision; JSON columns retain exact underlying values. This export is not a database backup.</p>{!owner && <p className="text-xs text-muted">Only a workspace owner can export records.</p>}</div>
    {error && <p role="alert" className="rounded-lg border border-danger p-3 text-sm text-danger">{error}</p>}{feedback && <p role="status" className="text-sm text-ok">{feedback}</p>}
    {query.isError ? <p role="alert" className="text-sm text-danger">The directory could not load. Your export selection is preserved. <button type="button" className="text-brand underline" onClick={() => void query.refetch()}>Try directory again</button></p> : !query.data ? <LoadingState label="Loading lead directory" /> : <><p className="text-sm text-muted">{query.data.total} matching records; {rows.length} shown on page {view.page + 1}. Archived is separate from recorded contact status.</p>
      <div className="overflow-x-auto rounded-xl border border-line bg-surface"><table className="w-full text-sm"><thead className="bg-soft"><tr>{["Export", "Lead / enquiry", "Company", "Contact", "Source", "Status"].map(label => <th key={label} className="p-3 text-left">{label}</th>)}</tr></thead><tbody>{rows.map(lead => <tr key={lead.id} className="border-t border-line align-top"><td className="p-3"><input type="checkbox" aria-label={"Select " + (lead.name || lead.id) + " for export"} checked={selected.has(lead.id)} disabled={!owner || exporting || !selected.has(lead.id) && selected.size >= 1000} onChange={event => directory.select([lead.id], event.target.checked)} /></td><td className="p-3 min-w-44"><Link className="text-brand font-medium underline break-words" to={"/leads/" + lead.id + "?tab=data"}>{lead.name || "Unnamed enquiry"}</Link><p className="text-xs text-muted mt-1">Data revision {lead.data_revision || 0}</p>{!!lead.truncated_fields?.length && <p className="text-xs text-warn">Long historical fields are shortened here. Open Lead data to review the full values.</p>}{lead.archived_at && <span className="inline-block mt-1 rounded bg-soft px-2 py-1 text-xs font-medium">Archived</span>}</td><td className="p-3 break-words">{lead.company || "Unknown"}</td><td className="p-3 min-w-48"><p className="break-words">{lead.email || "Unknown email"}</p><p className="text-muted break-words">{lead.normalized_phone || lead.phone || "Unknown phone"}</p></td><td className="p-3 break-words">{leadSourceLabels[lead.source] || lead.source}</td><td className="p-3"><span className={"text-xs font-medium " + (["OPTED_OUT", "SUPPRESSED"].includes(lead.status) ? "text-danger" : "text-muted")}>{lead.status.replaceAll("_", " ")}</span></td></tr>)}</tbody></table>{!rows.length && <p className="p-4 text-sm text-muted">No records match these filters. Choose another archive view or clear the search.</p>}</div>
      <div className="flex flex-wrap gap-4 items-center text-sm"><button type="button" disabled={view.page === 0 || query.isFetching} onClick={directory.previous} className="text-brand disabled:opacity-40">Previous page</button><span>Page {view.page + 1}</span><button type="button" disabled={!query.data.has_more || !query.data.next_cursor || query.isFetching} onClick={directory.next} className="text-brand disabled:opacity-40">Next page</button><button type="button" disabled={query.isFetching} onClick={() => void query.refetch()} className="text-brand underline disabled:opacity-40">Refresh directory</button></div>
    </>}
  </section>;
}
