import {useEffect,useRef,useState} from "react";
import {useQueryClient} from "@tanstack/react-query";
import {api,ApiError} from "@/lib/api";
import {ApprovalReviewDialog} from "./approval-review-dialog";
type Sender={provider:string;from:string;reply_to?:string|null};
type Context={lead:{id:string;name:string};review_token:string|null;recipient:string|null;sender:Sender|null;configuration:{can_review:boolean;can_dispatch:boolean;hold_code:string|null;reason:string|null};contact_policy:{restricted:boolean;reason:string|null};reply_to_message:{id:string;subject:string|null;body:string|null}|null;pending_actions:{id:string;subject:string|null;status:string}[];pending_total:number;can_create:boolean;unavailable_reason:string|null};
type Revision={id:string;revision:number;envelope:{subject:string|null;body:string;scheduled_at:string|null;recipient:string|null;sender:Sender|null}};
type Result={command:{id:string;action_id:string;resulting_revision_id:string};prepared_revision:Revision;replayed?:boolean};
type Pending={key:string;body:Record<string,unknown>;rejected:boolean};
const field="mt-1 w-full rounded-lg border border-line bg-surface p-2 text-sm",button="rounded-lg border border-line px-3 py-2 text-sm disabled:opacity-50";
function explanation(error:unknown){return error instanceof ApiError&&error.body&&typeof error.body==="object"?(error.body as {error?:string}).error||"The request was not accepted.":"The result is unknown. Check the saved request before retrying.";}
function localTime(value:string|null){if(!value)return "";const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function MessageComposer({leadId,actionId=null,replyToMessageId=null,onClose}:{leadId:string;actionId?:string|null;replyToMessageId?:string|null;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),pendingRef=useRef<Pending|null>(null),qc=useQueryClient();
 const [context,setContext]=useState<Context|null>(null),[revision,setRevision]=useState<Revision|null>(null),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[schedule,setSchedule]=useState(""),[reason,setReason]=useState(""),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[pending,setPending]=useState<Pending|null>(null),[saved,setSaved]=useState<Result|null>(null),[review,setReview]=useState(false);
 useEffect(()=>{const node=dialog.current,previous=document.activeElement as HTMLElement|null;node?.showModal();return()=>{node?.close();previous?.focus();};},[]);
 async function load(replace=false){setLoading(true);try{const current=await api.get<Context>("/leads/"+leadId+"/composer"+(replyToMessageId?"?reply_to_message_id="+encodeURIComponent(replyToMessageId):""));setContext(current);if(actionId){const value=await api.get<{prepared_revision:Revision|null}>("/actions/"+actionId+"/approval");if(!value.prepared_revision)throw new Error("This action has no current editable message.");setRevision(value.prepared_revision);if(replace){setSubject(value.prepared_revision.envelope.subject||"");setBody(value.prepared_revision.envelope.body);setSchedule(localTime(value.prepared_revision.envelope.scheduled_at));}}else if(replace&&current.reply_to_message?.subject)setSubject(/^Re:/i.test(current.reply_to_message.subject)?current.reply_to_message.subject:"Re: "+current.reply_to_message.subject);setError("");}catch(err){setError(explanation(err));}finally{setLoading(false);}}
 useEffect(()=>{void load(true);},[leadId,actionId,replyToMessageId]);
 function accepted(result:Result,key:string){if(pendingRef.current?.key!==key)return;pendingRef.current=null;setPending(null);setBusy(false);setError("");setSaved(result);for(const key of ["lead-outbound","outbound-summary","lead-timeline","activity-feed","dashboard-attention"])void qc.invalidateQueries({queryKey:[key]});}
 async function send(item:Pending){if(pendingRef.current?.key!==item.key)return;setBusy(true);setError("");try{const result=actionId?await api.put<Result>("/actions/"+actionId+"/composer",item.body):await api.post<Result>("/leads/"+leadId+"/composer",item.body);accepted(result,item.key);}catch(err){if(pendingRef.current?.key===item.key){const next={...item,rejected:err instanceof ApiError&&err.status>=400&&err.status<500};pendingRef.current=next;setPending(next);setError(explanation(err));}}finally{if(pendingRef.current?.key===item.key)setBusy(false);}}
 async function submit(){if(pendingRef.current||!context||busy)return;const key="composer-"+crypto.randomUUID();let scheduled:string|null=null;try{if(schedule)scheduled=new Date(schedule).toISOString();}catch{setError("Choose a valid local date and time.");return;}const item={key,rejected:false,body:{request_key:key,reason,subject,body,scheduled_at:scheduled,...(actionId?{expected_revision_id:revision?.id}:{review_token:context.review_token,acknowledge_pending:ack,kind:replyToMessageId?"REPLY":"NEW_MESSAGE",reply_to_message_id:replyToMessageId})}};pendingRef.current=item;setPending(item);await send(item);}
 async function lookup(){const item=pendingRef.current;if(!item)return;try{const result=await api.get<Result|{command:null}>("/composer/requests/"+encodeURIComponent(item.key));if(pendingRef.current?.key!==item.key)return;if(result.command)accepted(result as Result,item.key);else setError("No saved command is visible at this read. Keep the same request for retry.");}catch(err){if(pendingRef.current?.key===item.key)setError(explanation(err));}}
 if(review&&saved)return <ApprovalReviewDialog actionIds={[saved.command.action_id]} onClose={onClose}/>;
 const sender=actionId?revision?.envelope.sender:context?.sender,recipient=actionId?revision?.envelope.recipient:context?.recipient;
 return <dialog ref={dialog} aria-label="Message composer" onCancel={e=>{if(busy||pending&&!pending.rejected)e.preventDefault();else onClose();}} className="fixed inset-0 m-auto w-[min(94vw,760px)] max-h-[92dvh] overflow-y-auto rounded-2xl border border-line bg-surface p-6 text-ink shadow-2xl backdrop:bg-black/50">
 <header className="flex items-center justify-between gap-4"><h2 className="text-xl font-semibold">{actionId?"Edit message and schedule":replyToMessageId?"Reply to this enquiry":"Write a new message"}</h2><button type="button" aria-label="Close composer" className={button} disabled={busy||Boolean(pending&&!pending.rejected)} onClick={onClose}>Close</button></header>
 <p className="mt-2 text-sm text-muted">Save a draft, then review its exact recipient, sender and content. Saving does not send a message.</p>
 {loading&&<p role="status" className="py-6">Loading current recipient and settings...</p>}{error&&<div role="alert" className="my-4 rounded-lg border border-warn p-3 text-sm"><p>{error}</p>{!pending&&<button type="button" className={button} onClick={()=>void load(false)}>Review latest context with this draft</button>}</div>}
 {saved?<section className="my-6 space-y-3" aria-label="Saved composer result"><p role="status">Draft saved as revision {saved.prepared_revision.revision}. Approval is still required.</p><p className="text-sm">Request reference: {saved.command.id}</p><button type="button" className={button+" bg-brand text-white"} onClick={()=>setReview(true)}>Review saved draft</button></section>:context&&<form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();void submit();}}>
 <dl className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-2 rounded-lg bg-soft p-4 text-sm"><dt>To</dt><dd>{recipient||"Unavailable"}</dd><dt>From</dt><dd>{sender?.from||"Unavailable"}</dd><dt>Reply-To</dt><dd>{sender?.reply_to||"Not configured"}</dd></dl>
 {!context.can_create&&!actionId&&<p role="alert" className="text-sm text-warn">This enquiry cannot create an email draft: {context.unavailable_reason}. Review its contact policy or email setup.</p>}
 {context.configuration.hold_code&&<p className="text-sm text-warn">Live channel held: {context.configuration.reason}</p>}{sender?.provider==="sandbox"&&<p className="text-sm text-muted">Sandbox simulation. This does not deliver a real email.</p>}
 {context.reply_to_message&&<details><summary className="cursor-pointer text-sm">Original inbound message</summary><p className="whitespace-pre-wrap rounded-lg bg-soft p-3 text-sm">{context.reply_to_message.body||"Original body unavailable"}</p></details>}
 {!actionId&&context.pending_total>0&&<div className="space-y-2 rounded-lg border border-line p-3"><p className="text-sm">{context.pending_total} email action(s) already await completion.</p><ul className="text-xs text-muted">{context.pending_actions.map(row=><li key={row.id}>{row.subject||"Existing message"} ({row.status})</li>)}</ul><label className="flex gap-2 text-sm"><input aria-label="Acknowledge existing pending messages" type="checkbox" checked={ack} disabled={Boolean(pending)} onChange={e=>setAck(e.target.checked)}/>I reviewed these and intend to create a separate message.</label></div>}
 <label className="block text-sm">Subject<input aria-label="Composer subject" className={field} maxLength={200} required value={subject} disabled={Boolean(pending)} onChange={e=>setSubject(e.target.value)}/></label>
 <label className="block text-sm">Message<textarea aria-label="Composer message" className={field+" min-h-44"} maxLength={10000} required value={body} disabled={Boolean(pending)} onChange={e=>setBody(e.target.value)}/></label>
 <label className="block text-sm">Earliest send time (your local time, optional)<input aria-label="Composer schedule" type="datetime-local" className={field} value={schedule} disabled={Boolean(pending)} onChange={e=>setSchedule(e.target.value)}/></label><p className="text-xs text-muted">A scheduled time does not approve or guarantee delivery. All sending controls still apply.</p>
 <label className="block text-sm">Reason for this message or change<textarea aria-label="Composer reason" className={field} required maxLength={2000} value={reason} disabled={Boolean(pending)} onChange={e=>setReason(e.target.value)}/></label>
 {pending?<section aria-label="Composer request recovery" className="space-y-2 rounded-lg border border-line p-3"><p className="break-all text-xs">Request: {pending.key}</p><button type="button" className={button} onClick={()=>void lookup()}>Check saved draft request</button>{pending.rejected?<button type="button" className={button} disabled={busy} onClick={()=>{pendingRef.current=null;setPending(null);void load(false);}}>Review rejected draft</button>:<button type="button" className={button} disabled={busy} onClick={()=>void send(pending)}>Retry exact draft request</button>}<p className="text-xs text-muted">Draft text stays in this page memory. Confirm this request before closing or starting another message.</p></section>:<button className={button+" bg-brand text-white"} disabled={busy||loading||(!actionId&&!context.can_create)||(!actionId&&context.pending_total>0&&!ack)}>{actionId?"Save new reviewed revision":"Save draft for review"}</button>}
 </form>}
 </dialog>;
}
