import {useQuery} from "@tanstack/react-query";
import {Link} from "react-router-dom";
import {api} from "@/lib/api";
const button="rounded-lg border border-line px-3 py-2 text-sm disabled:opacity-50";
type Status={as_of:string;counts:Record<string,number>;oldest_age_seconds:Record<string,number|null>;sending:{allowed?:boolean;reason?:string;policy_valid:boolean;usage:{attempts_used:number};controls:{daily_attempt_limit:number;paused?:boolean}};ai:{admitted_attempts:number;limits:{max_daily_attempts:number}};alerts:{code:string;severity:string;title:string;runbook:string}[];alert_delivery:"IN_APP_ONLY"};
const guides:Record<string,{path:string;label:string;description:string}>={
 "policy-backlog":{path:"/event-recovery",label:"Review inbound processing",description:"Review pending mandatory contact policy before continuing outreach. Keep sending paused while an opt-out or suppression event is unresolved."},
 "uncertain-send":{path:"/outbound",label:"Reconcile provider outcome",description:"Inspect the original action and provider evidence. Use its recovery controls; a new action is not a safe substitute for an unknown send result."},
 "event-recovery":{path:"/event-recovery",label:"Review background recovery",description:"Inspect the held event and its recorded failure. Repair the cause before requesting the existing bounded retry."},
 "analysis-backlog":{path:"/intelligence",label:"Inspect analysis work",description:"Review queued jobs, failed items and provider limits. A pending analysis does not establish current intelligence."},
 "human-work":{path:"/conversations",label:"Review enquiry work",description:"Open the enquiry, inspect the latest reply and complete or reschedule its internal reminder. Review any blocked workflow separately."},
 "quota-review":{path:"/settings?tab=sending",label:"Inspect sending controls",description:"Reconcile usage and configured limits before increasing a budget. AI allowances are managed separately in AI assistance."}
};
function label(value:string){return value.toLowerCase().replaceAll("_"," ");}
export function OperationsStatus(){
 const query=useQuery({queryKey:["operations-status"],queryFn:()=>api.get<Status>("/operations/status"),refetchInterval:30000});
 return <section className="max-w-5xl space-y-5" aria-labelledby="operations-title"><h2 id="operations-title" className="text-xl font-semibold">Workspace operations</h2><p className="text-sm text-muted">Recorded backlog, sending allowances and issues requiring owner attention. Alerts appear in this application; external alert delivery and deployment monitoring need an operating service.</p><div className="flex flex-wrap gap-3"><button className={button} disabled={query.isFetching} onClick={()=>void query.refetch()}>Refresh operational status</button><Link className={button} to="/settings?tab=sending">Sending controls and pause</Link><Link className={button} to="/settings?tab=ai">AI allowances and usage</Link></div>
 {query.isPending?<p>Loading current operations...</p>:query.isError?<p role="alert">Operational status is unavailable. Inspect the deployment and refresh; missing data is not an all-clear.</p>:<><p className="text-xs text-muted">Observed {new Date(query.data.as_of).toLocaleString()}. This screen refreshes every 30 seconds while open.</p>
 <div className="space-y-3"><h3 className="font-semibold">Attention</h3>{query.data.alerts.length?query.data.alerts.map(alert=>{const guide=guides[alert.runbook];return <article key={alert.code} className="rounded-lg border border-line bg-surface p-4 space-y-2"><p className="text-xs font-medium">{label(alert.severity)}</p><h4 className="font-semibold">{alert.title}</h4>{guide&&<><p className="text-sm text-muted">{guide.description}</p><Link className="inline-block text-sm text-brand underline" to={guide.path}>{guide.label}</Link></>}</article>;}):<p className="text-sm rounded-lg border border-line p-4">No configured in-app alert rule currently matches these observations. This does not certify the deployment or provider.</p>}</div>
 <div className="grid gap-4 sm:grid-cols-2"><section className="rounded-lg border border-line bg-surface p-4 space-y-2"><h3 className="font-semibold">Work awaiting attention</h3><dl className="space-y-2">{Object.entries(query.data.counts).map(([key,value])=><div className="flex justify-between gap-4 text-sm" key={key}><dt>{key==="leads"?"Stored enquiries (including verification records)":label(key)}</dt><dd className="font-medium">{value}</dd></div>)}</dl></section><section className="rounded-lg border border-line bg-surface p-4 space-y-3"><h3 className="font-semibold">Current allowances</h3><p className="text-sm">Send attempts used: {query.data.sending.usage.attempts_used} / {query.data.sending.controls.daily_attempt_limit}</p><p className="text-sm">AI attempts admitted: {query.data.ai.admitted_attempts} / {query.data.ai.limits.max_daily_attempts}</p><p className="text-xs text-muted">Attempts and allowances do not measure customer outcomes or total hosting and support cost.</p><h3 className="font-semibold">Oldest waiting work</h3>{Object.entries(query.data.oldest_age_seconds).map(([key,seconds])=><p key={key} className="text-sm">{label(key)}: {seconds===null?"No usable timestamp":Math.floor(seconds/60)+" minutes"}</p>)}</section></div></>}
 </section>;
}
