import type { CurrentnessReason, IntelligenceInputRevisions, RecommendationComparison, RecommendationDescriptor } from "@/types/intelligence-currentness";
import { intelligenceFieldLabel } from "@/types/intelligence-currentness";
export function InputRevisions({ revisions }: { revisions: IntelligenceInputRevisions | null }) { return <p className="text-xs text-muted">{revisions ? "Business profile revision " + revisions.profile_revision + "; enquiry revision " + revisions.enquiry_revision + "; contact revision " + revisions.data_revision + "." : "Input revision details were not recorded for this historical result."}</p>; }
export function CurrentnessReasonText({ reason }: { reason: CurrentnessReason }) {
  const descriptions: Record<string, string> = { POLICY_CHANGED: "Freshness policy changed", PROFILE_CHANGED: "Business profile changed", ENQUIRY_CHANGED: "Enquiry context changed", LEAD_DATA_CHANGED: "Contact details changed", SOURCES_CHANGED: "Saved source evidence changed", FRESHNESS_CHANGED: "Source freshness changed", LEGACY_ASSESSMENT_REQUIRED: "Earlier analysis needs the current freshness assessment" };
  const label = descriptions[reason.code] || reason.code.replaceAll("_", " ").toLowerCase();
  return <>{label.charAt(0).toUpperCase() + label.slice(1)}{reason.fields.length ? ": " + reason.fields.map(intelligenceFieldLabel).join(", ") : ""}</>;
}
export function RecommendationChanges({ comparison }: { comparison: RecommendationComparison }) {
  const comparable = comparison.current?.step != null && comparison.current?.reason != null && comparison.previous?.step != null && comparison.previous?.reason != null;
  const same = comparison.current && comparison.previous && comparison.current.step === comparison.previous.step && comparison.current.reason === comparison.previous.reason;
  return <section aria-label="Recommendation changes" className="rounded-xl border border-line bg-surface p-4 space-y-4"><div><h3 className="font-semibold">Recommendation changes</h3><p className="mt-1 text-sm text-muted">Compare recorded inputs and recommendations. A changed input does not by itself explain why a particular decision changed.</p></div>
    {!comparison.current && <p className="text-sm text-warn">No current recommendation is available. Any previous result below is historical and must be reviewed again against current inputs.</p>}
    {comparison.current && comparison.previous && <p className="text-sm font-medium">{!comparable ? "Historical recommendation details are incomplete; a full comparison is unavailable." : same ? "The recorded recommendation is unchanged across these runs." : "The recorded recommendation differs from the previous run."}</p>}
    {!comparison.previous && <p className="text-sm text-muted">No earlier completed recommendation is available for comparison.</p>}
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">{comparison.previous && <Descriptor title="Previous recommendation - historical" descriptor={comparison.previous} />}{comparison.current && <Descriptor title="Current recommendation" descriptor={comparison.current} />}</div>
    {comparison.input_changes.length > 0 && <div className="space-y-2"><h4 className="text-sm font-medium">Recorded input differences</h4><ul className="list-disc pl-5 text-sm text-muted">{comparison.input_changes.map((reason, index) => <li key={index}><CurrentnessReasonText reason={reason} /></li>)}</ul></div>}
    {comparison.limitations.length > 0 && <ul className="space-y-1 text-xs text-muted">{comparison.limitations.map((text, index) => <li key={index}>{text}</li>)}</ul>}
  </section>;
}
function Descriptor({ title, descriptor }: { title: string; descriptor: RecommendationDescriptor }) { return <article className="min-w-0 rounded-lg border border-line bg-soft p-3 space-y-2"><h4 className="text-sm font-semibold">{title}</h4><p className="text-sm">{descriptor.step ? descriptor.step.replaceAll("_", " ").toLowerCase() : "Recorded step unavailable"}</p><p className="break-words text-sm">{descriptor.reason || "Recorded reason unavailable"}</p><p className="text-xs text-muted">Recorded {new Date(descriptor.created_at).toLocaleString()}</p><InputRevisions revisions={descriptor.revisions} /><details><summary className="text-xs text-brand cursor-pointer">Recorded result references</summary><p className="mt-1 break-all text-xs text-muted">Recommendation {descriptor.id}; snapshot {descriptor.snapshot_id}.</p></details></article>; }
