export const PIPELINE_VERSION = "m2.0-deterministic-v1";

export const SNAPSHOT_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  READY: "READY",
  SUPERSEDED: "SUPERSEDED",
  FAILED: "FAILED"
});

export const INTELLIGENCE_STATUS = Object.freeze({
  NOT_RUN: "NOT_RUN",
  READY_TO_RUN: "READY_TO_RUN",
  GENERATED: "GENERATED",
  NEEDS_DATA: "NEEDS_DATA",
  FAILED: "FAILED"
});

export const CONFIDENCE = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH"
});

export const EVIDENCE_SOURCE_TYPES = Object.freeze({
  CUSTOMER_PROVIDED: "CUSTOMER_PROVIDED",
  CSV: "CSV",
  MANUAL: "MANUAL"
});

export const CLAIM_FIELDS = Object.freeze({
  ENQUIRY_INTEREST: "ENQUIRY_INTEREST",
  ENQUIRY_LOCATION: "ENQUIRY_LOCATION",
  ENQUIRY_BUDGET: "ENQUIRY_BUDGET",
  ENQUIRY_TIMELINE: "ENQUIRY_TIMELINE",
  ENQUIRY_DATE: "ENQUIRY_DATE",
  ENQUIRY_LAST_INTERACTION: "ENQUIRY_LAST_INTERACTION",
  LEAD_NAME: "LEAD_NAME",
  COMPANY_NAME: "COMPANY_NAME",
  CONTACT_EMAIL: "CONTACT_EMAIL",
  CONTACT_PHONE: "CONTACT_PHONE",
  LEAD_SOURCE: "LEAD_SOURCE",
  PROVENANCE: "PROVENANCE"
});

export const SIGNAL_TYPES = Object.freeze({
  CONTACT_INFORMATION_AVAILABLE: "CONTACT_INFORMATION_AVAILABLE",
  COMPANY_PROVIDED: "COMPANY_PROVIDED",
  COMPANY_MISSING: "COMPANY_MISSING",
  EMAIL_AVAILABLE: "EMAIL_AVAILABLE",
  PHONE_AVAILABLE: "PHONE_AVAILABLE",
  DUPLICATE_WARNING: "DUPLICATE_WARNING",
  DATA_INCOMPLETE: "DATA_INCOMPLETE",
  PROVENANCE_AVAILABLE: "PROVENANCE_AVAILABLE",
  LEAD_REPLIED_POSITIVE: "LEAD_REPLIED_POSITIVE",
  LEAD_REPLIED_NEGATIVE: "LEAD_REPLIED_NEGATIVE",
  LEAD_ASKED_QUESTION: "LEAD_ASKED_QUESTION",
  LEAD_OPTED_OUT: "LEAD_OPTED_OUT",
  LEAD_REPLY_UNCLEAR: "LEAD_REPLY_UNCLEAR"
});

export const READINESS_STATUS = Object.freeze({
  READY_FOR_INTELLIGENCE: "READY_FOR_INTELLIGENCE",
  NEEDS_MORE_DATA: "NEEDS_MORE_DATA"
});

export const QUALIFICATION_STATUS = Object.freeze({
  FOUNDATION_READY: "FOUNDATION_READY",
  NEEDS_REVIEW: "NEEDS_REVIEW"
});

export const RECOMMENDATION_TYPES = Object.freeze({
  GATHER_MORE_DATA: "GATHER_MORE_DATA",
  REVIEW_LEAD: "REVIEW_LEAD",
  READY_FOR_RESEARCH: "READY_FOR_RESEARCH",
  RUN_INTELLIGENCE: "RUN_INTELLIGENCE",
  HUMAN_REVIEW: "HUMAN_REVIEW"
});

export const OUTBOUND_ACTION_TYPES = Object.freeze({
  SEND_EMAIL: "SEND_EMAIL",
  SEND_WHATSAPP: "SEND_WHATSAPP",
  CREATE_HUMAN_TASK: "CREATE_HUMAN_TASK"
});
